// hotels.ts

// Define the Hotel interface using camelCase naming conventions.
// The region property is now an array of region UUID strings.
export interface Hotel {
	uuid: string;
	name: string | null;
	region: string[] | null; // now an array of region UUIDs
	address: string | null;
	location: string | null;
	lat: number | null;
	lng: number | null;
	rating: number | null;
	contact: string | null; // storing phone numbers as strings
	email: string | null;
	website: string | null;
	facebook: string | null;
	instagram: string | null;
	petabookPartner: boolean; // converted to boolean
	shortDescription: string | null;
	longDescription: string | null;
	services: string | null;
	prices: number | null;
	reservationEmail: string | null;
	responsableName: string | null;
	conditions: string | null;
	workingHours: string | null;
	images: string[] | null;
	checkInHours: string | null;
	checkOutHours: string | null;
	checkInDays: string | null;
	checkOutDays: string | null;
	restrictions: string | null;
	gps?: {
		lat: number;
		lng: number;
	};
}

// A mapping type to index hotels by their uuid .
export interface HotelData {
	[uuid: string]: Hotel;
}

/*
  Region IDs (from your regionList):
    - Lisboa:      "c5d53de2-15e5-4fa8-a0f3-9c4b30b18a91"
    - Centro:      "ba9a11fa-3d9d-4d2b-90f8-6b987d0a2c34"
    - Porto:       "6e3c11f3-3a28-4e2b-bf9e-6713c45b0a6a"
    - Norte:       "f0d2c8a9-5f7a-4e30-b8a4-d3b9a8f7e6c5"
    - Arquipélagos:"ea3f9a57-2c8b-40d8-8f51-7f9f8d8a27cb"
    - Algarve:     "ae4d2c60-5f3f-4b2d-8e2d-7c2b8b6a9e42"
    - Alentejo:    "d1a5a76f-7a8f-4b92-9a3f-abc1d1e2f345"
*/

// The hotel list – note that "n.a." values have been converted to null.
// The region property is now an array of region UUIDs.
// For hotels originally from Lisbon, we add both "Lisboa" and "Centro".
// For hotels originally from Porto, we add both "Porto" and "Norte".
export const hotelList: Hotel[] = [
	// Hotels from Lisbon:
	{
		uuid: "1a2b3c4d-0001-0001-0001-000000000001",
		name: "Quinta da Patada",
		region: [
			"c5d53de2-15e5-4fa8-a0f3-9c4b30b18a91", // Lisboa
			"ba9a11fa-3d9d-4d2b-90f8-6b987d0a2c34", // Centro
		],
		address:
			"Rua do Murtal, Quinta da Patada Manjoeira, 2660-499 Santo Antão do Tojal",
		location: "Lisbon",
		lat: 38.876809,
		lng: -9.159942,
		rating: 4,
		contact: "912385650",
		email: "geral@quintadapatada.com",
		website: "https://quintadapatada.com/",
		facebook: "https://www.facebook.com/quintadapatada/",
		instagram: "https://www.instagram.com/quintadapatada/",
		petabookPartner: true,
		shortDescription:
			"A Quinta da Patada, em Loures, é um hotel para cães com hospedagem, creche e banhos, oferecendo supervisão 24 horas.",
		longDescription:
			"A Quinta da Patada, localizada em Santo Antão do Tojal, Loures, é um hotel para cães que oferece hospedagem, creche, banhos e tosquias, assegurando supervisão 24 horas por dia. Com uma área de 8000 m², proporciona atividades ao ar livre e cuidados personalizados em 25 boxes individuais, com áreas entre 10m² e 60m², incluindo zonas cobertas, descobertas e com sombra. A alimentação é premium, sem glúten e com condroprotetores, adaptada às necessidades energéticas de cada cão. Os visitantes podem agendar visitas para familiarizar os seus cães com o espaço e os tratadores. O hotel aposta em técnicas especializadas para minimizar a ansiedade e promove o bem-estar físico e emocional dos animais, mantendo os donos atualizados com fotos e vídeos através do WhatsApp.A Quinta da Patada garante, no mínimo, dois passeios diários e, para cães que cumpram as regras, a possibilidade de brincar soltos com outros cães durante todo o dia. O acompanhamento é personalizado, com suporte veterinário sempre que necessário, e elevados padrões de higiene e segurança. Além disso, oferece serviços de Banhos e Tosquias, permitindo que os cães brinquem à vontade antes de regressarem a casa limpos e cheirosos. Um serviço de transporte está disponível, assegurando o conforto do início ao fim da estadia. Desde a chegada, os cães recebem mimos e atenção para que se sintam felizes e bem cuidados.",
		services: "Hotel canino",
		prices: 17,
		reservationEmail: "geral@quintadapatada.com",
		responsableName: "",
		conditions: "",
		workingHours: "",
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
		images: [
			"/images/hoteis/quinta-da-patada/img-1.jpeg",
			"/images/hoteis/quinta-da-patada/img-10.jpeg",
			"/images/hoteis/quinta-da-patada/img-11.jpeg",
			"/images/hoteis/quinta-da-patada/img-12.jpeg",
			"/images/hoteis/quinta-da-patada/img-13.jpeg",
		],
	},
	{
		uuid: "1a2b3c4d-0002-0002-0002-000000000002",
		name: "Just4Buddies",
		region: [
			"c5d53de2-15e5-4fa8-a0f3-9c4b30b18a91",
			"ba9a11fa-3d9d-4d2b-90f8-6b987d0a2c34",
		],
		address: "Praceta Damião Peres 25, São Domingos de Rana",
		location: "Lisbon",
		lat: 38.710714,
		lng: -9.348297,
		rating: 4,
		contact: "911128070",
		email: "geral@just4buddies.pt",
		website: "https://just4buddies.pt/",
		facebook: "https://www.facebook.com/just4buddies?locale=pt_BR",
		instagram: "https://www.instagram.com/just4buddies/",
		petabookPartner: true,
		shortDescription:
			"A creche canina em Cascais garante dias felizes e estimulantes para os patudos.",
		longDescription:
			"A creche canina situada no concelho de Cascais tem como missão proporcionar dias alegres e estimulantes aos patudos, enquanto os seus donos estão a trabalhar ou de férias, sem preocupações. Baseando-se nos valores de transparência, integridade, responsabilidade e, acima de tudo, amor pelos fiéis amigos de quatro patas, esta creche oferece um ambiente seguro e carinhoso. As instalações incluem uma loja e uma treinadora que está disponível para ajudar a resolver qualquer situação, tanto dentro como fora das instalações.",
		services: "Hotel canino",
		prices: 18,
		reservationEmail: "geral@just4buddies.pt",
		responsableName: "",
		conditions: "",
		workingHours: "",
		images: [
			"/images/hoteis/just4buddies/img-1.jpg",
			"/images/hoteis/just4buddies/img-2.jpg",
			"/images/hoteis/just4buddies/img-3.jpg",
			"/images/hoteis/just4buddies/img-4.jpg",
			"/images/hoteis/just4buddies/img-5.jpg",
		],
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
	},
	{
		uuid: "1a2b3c4d-0003-0003-0003-000000000003",
		name: "Recreio Canino",
		region: [
			"c5d53de2-15e5-4fa8-a0f3-9c4b30b18a91",
			"ba9a11fa-3d9d-4d2b-90f8-6b987d0a2c34",
		],
		address: "Rua da Amoreira, Lousa",
		location: "Lisbon",
		lat: 38.894309,
		lng: -9.205765,
		rating: 4,
		contact: "210963508",
		email: "info@recreiocanino.com",
		website: "https://recreiocanino.com/",
		facebook: "https://www.facebook.com/RecreioCanino/?locale=pt_PT",
		instagram: "https://www.instagram.com/recreiocanino/",
		petabookPartner: false,
		shortDescription:
			"Recreio Canino promove socialização e bem-estar dos cães com serviços personalizados.",
		longDescription:
			"Recreio Canino é um espaço dedicado à socialização e bem-estar dos cães, proporcionando um ambiente seguro e estimulante para os animais. Fundado por Fernando Silva, que tem formação cinotécnica e experiência em treino canino, o projeto baseia-se na transparência, rigor e competência. A filosofia do Recreio Canino é permitir que os cães sejam simplesmente cães, promovendo um ambiente de liberdade e socialização saudável. A equipa combina experiência prática e conhecimento técnico, adquiridos através de formação na Associação Cinófila do Oeste (ACO) e participação em eventos especializados sobre comportamento e treino canino. Além da socialização, o espaço oferece serviços que atendem às necessidades dos donos e garantem o bem-estar dos seus animais de estimação. Localizado em Loures, o Recreio Canino funciona de segunda a sexta-feira, das 9h às 16h.",
		services: "Hotel canino",
		prices: 25,
		reservationEmail: null,
		responsableName: null,
		conditions: "",
		workingHours: "",
		images: [
			"/images/hoteis/recreio-canino/img-1.jpg",
			"/images/hoteis/recreio-canino/img-10.jpg",
			"/images/hoteis/recreio-canino/img-11.jpg",
			"/images/hoteis/recreio-canino/img-12.jpg",
			"/images/hoteis/recreio-canino/img-13.jpg",
			"/images/hoteis/recreio-canino/img-14.jpg",
		],
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
	},
	{
		uuid: "1a2b3c4d-0004-0004-0004-000000000004",
		name: "101 Hotel Canino",
		region: [
			"c5d53de2-15e5-4fa8-a0f3-9c4b30b18a91",
			"ba9a11fa-3d9d-4d2b-90f8-6b987d0a2c34",
		],
		address: "Quinta do Pinheirinho, R. dos Comerciantes, Pinhal Novo",
		location: "Pinhal Novo, Setubal",
		lat: 38.624182,
		lng: -8.871338,
		rating: 4,
		contact: "913847150",
		email: "101hotelcanino@gmail.com",
		website: "https://www.banhosetosquiasaodomicilio.pt/hotel-canino",
		facebook:
			"https://www.facebook.com/p/101-Servi%C3%A7os-para-C%C3%A3es-e-Gatos-ao-Domic%C3%ADlio-100063469993660/?locale=pt_BR",
		instagram: "https://www.instagram.com/101servicos/",
		petabookPartner: true,
		shortDescription:
			"O Hotel Canino 101 oferece instalações modernas com boxes privadas e parques espaçosos.",
		longDescription:
			"Localizado numa zona tranquila do Pinhal Novo, o Hotel Canino 101 oferece instalações modernas e confortáveis para cães. Com 20 boxes privadas de 8 m², cada uma equipada com cama, manta, bebedouro automático, comedouro ajustável e tapete aquecido, o espaço garante o bem-estar dos seus hóspedes. Os amplos parques de recreio, divididos em duas áreas com piscinas e bebedouros, permitem que os cães socializem e gastem energia durante o dia. Para famílias com mais de um cão, há a opção de partilhar a mesma box, reduzindo o stress da separação. Além das instalações, o hotel oferece serviços adicionais como banho e transporte, mediante pedido. Os donos podem acompanhar os momentos especiais dos seus cães através de vídeos enviados durante a estadia, trazendo tranquilidade e proximidade, mesmo à distância. O Hotel Canino 101 é dedicado a proporcionar uma experiência segura, confortável e cheia de diversão para os seus hóspedes de quatro patas.",
		services: "Hotel canino",
		prices: 12,
		reservationEmail: "101hotelcanino@gmail.com",
		responsableName: "",
		conditions: "",
		workingHours: "",
		images: [
			"/images/hoteis/hotel-101/img-1.jpg",
			"/images/hoteis/hotel-101/img-10.jpeg",
			"/images/hoteis/hotel-101/img-11.jpeg",
			"/images/hoteis/hotel-101/img-12.jpeg",
			"/images/hoteis/hotel-101/img-13.jpeg",
			"/images/hoteis/hotel-101/img-14.jpeg",
			"/images/hoteis/hotel-101/img-15.jpeg",
			"/images/hoteis/hotel-101/img-16.jpeg",
			"/images/hoteis/hotel-101/img-17.jpeg",
			"/images/hoteis/hotel-101/img-18.jpeg",
			"/images/hoteis/hotel-101/img-19.jpeg",
			"/images/hoteis/hotel-101/img-2.jpg",
			"/images/hoteis/hotel-101/img-20.jpeg",
			"/images/hoteis/hotel-101/img-21.jpeg",
			"/images/hoteis/hotel-101/img-22.jpeg",
			"/images/hoteis/hotel-101/img-3.jpg",
			"/images/hoteis/hotel-101/img-4.jpg",
			"/images/hoteis/hotel-101/img-5.jpg",
			"/images/hoteis/hotel-101/img-6.jpg",
			"/images/hoteis/hotel-101/img-7.jpg",
			"/images/hoteis/hotel-101/img-8.jpg",
			"/images/hoteis/hotel-101/img-9.jpg",
		],
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
	},
	{
		uuid: "1a2b3c4d-0005-0005-0005-000000000005",
		name: "Curti Dog",
		region: [
			"c5d53de2-15e5-4fa8-a0f3-9c4b30b18a91",
			"ba9a11fa-3d9d-4d2b-90f8-6b987d0a2c34",
		],
		address: "Rua Casal da Curtinha 13 2530, Reguengo Grande",
		location: "Pinhal Novo, Setubal",
		lat: 39.290316,
		lng: -9.226053,
		rating: 4,
		contact: "914819881",
		email: "curti_dog@hotmail.com",
		website: null,
		facebook: "https://www.facebook.com/CurtiDog18/?locale=pt_PT",
		instagram: "https://www.instagram.com/curti_dog/",
		petabookPartner: true,
		shortDescription:
			"A Curti Dog oferece hospedagem, creche e estética para cães e gatos, com serviços de petshop, adestramento e transporte.",
		longDescription:
			"A Curti Dog é uma empresa familiar que foi estabelecida em 2018 e está situada na zona oeste. Esta empresa oferece uma variedade de serviços para cães e gatos, incluindo hospedagem e creche. Durante o dia, os animais têm acesso a um espaço aberto, enquanto à noite, cada um é acomodado em uma box individual com sistemas de proteção contra frio, chuva e calor. Além das opções de hospedagem, a Curti Dog disponibiliza serviços de estética animal, que incluem tosquias, banhos e tratamentos para o pelo e a pele. A empresa também conta com uma petshop, oferece treinamentos de adestramento canino, transportes para consultas veterinárias e serviços de lavanderia. Para manter os donos informados e tranquilos, são realizadas publicações diárias com vídeos e fotos dos hóspedes.",
		services: "Hotel canino",
		prices: 10,
		reservationEmail: "curti_dog@hotmail.com",
		responsableName: "",
		conditions: "",
		workingHours: "",
		images: [
			"/images/hoteis/curti-dog/img-1.jpeg",
			"/images/hoteis/curti-dog/img-2.jpeg",
			"/images/hoteis/curti-dog/img-3.jpeg",
			"/images/hoteis/curti-dog/img-4.jpeg",
			"/images/hoteis/curti-dog/img-5.jpeg",
			"/images/hoteis/curti-dog/img-6.jpeg",
		],
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
	},
	{
		uuid: "1a2b3c4d-0006-0006-0006-000000000006",
		name: "Sweetpet",
		location: "Lisboa",
		lat: 38.716445,
		lng: -9.272457,
		rating: 4,
		region: [
			"c5d53de2-15e5-4fa8-a0f3-9c4b30b18a91",
			"ba9a11fa-3d9d-4d2b-90f8-6b987d0a2c34",
		],
		address: "Caminho das Batatas nº 2, Queijas",
		contact: "912269890",
		email: "info@sweetpet.pt",
		website: "https://www.sweetpet.pt/",
		facebook: "https://www.facebook.com/sweetpetcascais/?locale=pt_PT",
		instagram: "https://www.instagram.com/sweetpet/",
		petabookPartner: false,
		shortDescription:
			"Sweetpet oferece um ambiente holístico para o bem-estar canino com serviços de saúde, educação e socialização.",
		longDescription:
			"A SweetPet, situada em Queijas com serviço de recolha em Lisboa, é um centro de bem-estar para cães que adota uma abordagem holística no cuidado destes animais, tratando-os como membros da família. O espaço está desenhado para fomentar a saúde, felicidade e sociabilidade canina, oferecendo serviços integrados de exercício, relaxamento, saúde, nutrição, higiene, educação e socialização. As instalações estendem-se por uma quinta de 9.000 m², equipada com três parques, uma piscina, diversas árvores e um chalet para descanso à sombra, proporcionando um ambiente ideal para brincadeiras, socialização e relaxamento. A SweetPet dispõe ainda de serviços de saúde, incluindo check-ups, vacinação e diagnósticos, bem como programas de educação focados em comportamento e obediência, com planos personalizados. Os requisitos para admissão na creche incluem uma avaliação comportamental e a comprovação de todas as vacinas em dia, incluindo a vacina da tosse dos canis. Machos com mais de 10 meses devem ser esterilizados e cadelas no cio não são aceites.",
		services: "Hotel canino",
		prices: 20,
		reservationEmail: null,
		responsableName: null,
		conditions: "",
		workingHours: "",
		images: [
			"/images/hoteis/sweetpet/img-1.jpg",
			"/images/hoteis/sweetpet/img-2.jpg",
			"/images/hoteis/sweetpet/img-3.jpg",
			"/images/hoteis/sweetpet/img-4.jpg",
			"/images/hoteis/sweetpet/img-5.jpg",
			"/images/hoteis/sweetpet/img-6.jpg",
			"/images/hoteis/sweetpet/img-7.jpg",
		],
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
	},
	// Hotels from Porto:
	{
		uuid: "1a2b3c4d-0009-0009-0009-000000000009",
		name: "Pet Hotel Gaia",
		region: [
			"6e3c11f3-3a28-4e2b-bf9e-6713c45b0a6a", // Porto
			"f0d2c8a9-5f7a-4e30-b8a4-d3b9a8f7e6c5", // Norte
		],
		address: "Rua Mata 798, Vila Nova de Gaia",
		location: "Vila Nova de Gaia, Porto",
		lat: 41.107207,
		lng: -8.570766,
		rating: 4,
		contact: "227840230",
		email: null,
		website: "https://pethotelgaia.com/",
		facebook: "https://www.facebook.com/pethotelgaia/?locale=pt_PT",
		instagram: "https://www.instagram.com/pet.hotel.gaia/",
		petabookPartner: false,
		shortDescription:
			"Pet Hotel Gaia oferece alojamento para cães e gatos com passeios diários e apoio veterinário, com opções de estadia Outdoor e Indoor.",
		longDescription:
			"O Pet Hotel Gaia, localizado em Vila Nova de Gaia, oferece alojamento para cães e gatos, com serviços que incluem passeios diários, zona de diversão, e apoio veterinário. O Hotel Canino oferece estadias Outdoor (ideal para cães de médio e grande porte) e estadias Indoor (ideal para cães de pequeno porte). Ao deixar o seu cão no Pet Hotel Gaia serviços como água fresca, uma cama confortável, passeios diários, diversão e apoio veterinário estão incluídos nas férias dos pets.",
		services: "Hotel canino",
		prices: 16,
		reservationEmail: null,
		responsableName: null,
		conditions: "",
		workingHours: "",
		images: [
			"/images/hoteis/pet-hotel-gaia/img-1.jpg",
			"/images/hoteis/pet-hotel-gaia/img-10.jpg",
			"/images/hoteis/pet-hotel-gaia/img-11.jpg",
			"/images/hoteis/pet-hotel-gaia/img-12.jpeg",
			"/images/hoteis/pet-hotel-gaia/img-13.jpeg",
			"/images/hoteis/pet-hotel-gaia/img-3.png",
			"/images/hoteis/pet-hotel-gaia/img-8.jpg",
			"/images/hoteis/pet-hotel-gaia/img-9.jpg",
		],
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
	},
	{
		uuid: "1a2b3c4d-0010-0010-0010-000000000010",
		name: "Domi Canis Cattus EcoHotel",
		region: [
			"6e3c11f3-3a28-4e2b-bf9e-6713c45b0a6a",
			"f0d2c8a9-5f7a-4e30-b8a4-d3b9a8f7e6c5",
		],
		address: "Rua da Cunha 140, Parada, Vila do Conde",
		location: "Vila do Conde",
		lat: 41.362698,
		lng: -8.645343,
		rating: 4,
		contact: "913274697",
		email: "domicaniscattus@gmail.com",
		website: null,
		facebook: "https://www.facebook.com/Ruicosta2016/?locale=pt_PT",
		instagram: "https://www.instagram.com/dcc_domi_canis_cattus/",
		petabookPartner: true,
		shortDescription:
			"O Domi Canis Cattus EcoHotel combina design inovador e conforto para animais, sendo premiado e reconhecido internacionalmente.",
		longDescription:
			'O Domi Canis Cattus EcoHotel é uma obra-prima da arquitetura contemporânea, concebida para proporcionar o máximo conforto e bem-estar aos seus hóspedes de quatro patas. Desde a sua conceção em 2015 até à abertura ao público em 2019, o projeto consolidou-se como um dos espaços mais inovadores e premiados no setor de hospitalidade para animais. Localizado no distrito do Porto, foi distinguido com o prémio 5 Estrelas Regiões 2020, sendo reconhecido como o melhor na sua categoria. Mais do que um simples alojamento, destaca-se pela sua infraestrutura de vanguarda, cuidadosamente desenhada para criar um ambiente seguro, funcional e visualmente deslumbrante. A excelência do Domi Canis Cattus EcoHotel tem sido amplamente reconhecida a nível internacional, com uma impressionante coleção de prémios como o International Design Award, DNA Paris Design Awards e Muse Design Awards. Celebrado por instituições de renome como o Chicago Athenaeum e os Urban Design & Architecture Design Awards, o hotel foi consagrado como o "Pet Hotel mais bonito do mundo" em 2022. Devidamente licenciado pela CMVC e pela DGAV, reflete um compromisso com os mais altos padrões de qualidade e regulamentação, oferecendo uma experiência única e inesquecível tanto para os animais como para os seus tutores.',
		services: "Hotel canino",
		prices: 25,
		reservationEmail: "domicaniscattus@gmail.com",
		responsableName: "",
		conditions: "",
		workingHours: "",
		images: [
			"/images/hoteis/domi-cannis-catus/img-1.jpg",
			"/images/hoteis/domi-cannis-catus/img-10.jpg",
			"/images/hoteis/domi-cannis-catus/img-11.jpg",
		],
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
	},
	{
		uuid: "1a2b3c4d-0011-0011-0011-000000000011",
		name: "Pet Home",
		region: [
			"6e3c11f3-3a28-4e2b-bf9e-6713c45b0a6a",
			"f0d2c8a9-5f7a-4e30-b8a4-d3b9a8f7e6c5",
		],
		address: "Zona Industrial Arcos de Sadrão 401, Vila Nova de Gaia",
		location: "Pinhal Novo, Setubal",
		lat: 41.116894,
		lng: -8.580968,
		rating: 4,
		contact: "935094048",
		email: "geral.pet.home@gmail.com",
		website: "https://pethomept.wixsite.com/pethome",
		facebook: "https://pethomept.wixsite.com/pethome",
		instagram: "https://www.instagram.com/_pet.home_/",
		petabookPartner: false,
		shortDescription:
			"A Pet Home foi criada por enfermeiras veterinárias e educadoras caninas, oferecendo hotel, creche, treino e serviços estéticos.",
		longDescription:
			"A Pet Home, localizada na Zona Industrial dos Arcos de Sardão em Vila Nova de Gaia, foi criada por duas colegas de turma de Enfermagem Veterinária e educadoras caninas, com a visão de mudar e melhorar o mundo animal. Oferece uma gama de serviços incluindo treino canino, consultas de comportamento, creche e hotel canino, além de banhos e tosquias. Neste hotel, o pets têm acesso à creche canina da Pet Home. Cada animal tem direito a uma box individual (exceto para membros da mesma família, que podem ficar juntos). No fim-de-semana, os cães do hotel têm acesso à creche de manhã e ao final do dia. Na Pet Home, cada pet deve trazer a sua própria comida, para evitar grandes mudanças durante a sua estadia. O acompanhamento da estadia do seu patudo pode ser feita através das redes sociais. Deve efetuar o pagamento de 50% do valor total ao fazer a reserva.",
		services: "Hotel canino",
		prices: 0,
		reservationEmail: null,
		responsableName: null,
		conditions: "",
		workingHours: "",
		images: [
			"/images/hoteis/pet-home/2nd-try/img-1.jpg",
			"/images/hoteis/pet-home/2nd-try/img-2.jpg",
			"/images/hoteis/pet-home/2nd-try/img-3.jpg",
			"/images/hoteis/pet-home/2nd-try/img-4.jpg",
			"/images/hoteis/pet-home/2nd-try/img-5.jpg",
			"/images/hoteis/pet-home/2nd-try/img-6.jpg",
			"/images/hoteis/pet-home/2nd-try/img-7.jpg",
		],
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
	},
	{
		uuid: "1a2b3c4d-0012-0012-0012-000000000012",
		name: "Pets and Family",
		region: [
			"6e3c11f3-3a28-4e2b-bf9e-6713c45b0a6a",
			"f0d2c8a9-5f7a-4e30-b8a4-d3b9a8f7e6c5",
		],
		address: "Rua Nova do Arquinho 426, Maia",
		location: "Maia",
		lat: 41.207731,
		lng: -8.600419,
		rating: 4,
		contact: "912741229",
		email: null,
		website: "https://petsandfamily.pt/",
		facebook: "https://www.facebook.com/petsandfamilypt/?locale=pt_BR",
		instagram: "https://www.instagram.com/pets.and.family/",
		petabookPartner: false,
		shortDescription:
			"Pets and Family oferece creche e hotel canino sem espaços confinados, com avaliação inicial para segurança e adaptação.",
		longDescription:
			"A Pets and Family, localizada na Maia, oferece um serviço diferenciado de creche e hotel canino, funcionando das 8h às 20h. Diferencia-se por não utilizar espaços confinados, tratando os animais como membros da família, com atenção 24 horas por parte dos tratadores, promovendo a socialização e atividade física em ambiente familiar. Neste hotel, os animais desfrutam de liberadade de circulação e de socialização com os restantes animais hospedados. Para garantir uma segurança eficaz, se for a primeira vez do pet no hotel, um teste será feito para avaliar a forma como este reage com os restantes patudos do hotel. Em termos de preços, uma estadia fica a 18,5 € por noite, havendo vários descontos concedidos, consoante o numero de cães da mesma família e se é ou não cliente da creche canina.",
		services: "Hotel canino",
		prices: 19,
		reservationEmail: null,
		responsableName: null,
		conditions: "",
		workingHours: "",
		images: [
			"/images/hoteis/pets-and-family/img-1.jpg",
			"/images/hoteis/pets-and-family/img-2.jpg",
			"/images/hoteis/pets-and-family/img-3.jpg",
			"/images/hoteis/pets-and-family/img-4.jpg",
		],
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
	},
	// Hotels from Norte (already have region "Norte")
	{
		uuid: "1a2b3c4d-0013-0013-0013-000000000013",
		name: "Nortdog",
		region: ["f0d2c8a9-5f7a-4e30-b8a4-d3b9a8f7e6c5"],
		address: "Avenida de Santo André, nº 163, Braga",
		location: "Braga",
		lat: 41.541679,
		lng: -8.453439,
		rating: 4,
		contact: "965070933",
		email: "geral@nortdog.pt",
		website: "https://nortdog.pt/",
		facebook: "https://www.facebook.com/nortdogbraga/?locale=pt_PT",
		instagram: "https://www.instagram.com/nortdog_petinnature/",
		petabookPartner: false,
		shortDescription:
			"Nortdog, com 25 anos de experiência, oferece hotel, creche e treino para cães e gatos, com eventos solidários.",
		longDescription:
			'A Nortdog é uma academia para cães e gatos situada em Braga, Portugal, com uma trajetória de 25 anos, oferecendo uma vasta seleção de produtos e serviços para estes animais. Esta entidade é reconhecida pelo seu compromisso com o bem-estar animal, permitindo que os pets aproveitem a natureza nas suas instalações, que incluem hotéis para caninos e felinos, creches para ambos, bem como cursos de obediência e treino personalizado. Adicionalmente, a Nortdog organiza eventos como a "Aqua Dog Party", um evento que mistura diversão aquática para os cães com uma componente social, redirecionando uma parte das receitas para associações de proteção animal locais. As instalações da academia são desenhadas para assegurar conforto e segurança, com espaços amplos e naturais, música ambiente, e cuidado contínuo aos animais hospedados.',
		services: "Hotel canino",
		prices: 16,
		reservationEmail: null,
		responsableName: null,
		conditions: "",
		workingHours: "",
		images: [
			"/images/hoteis/nortdog/img-1.jpg",
			"/images/hoteis/nortdog/img-2.jpg",
			"/images/hoteis/nortdog/img-3.jpg",
			"/images/hoteis/nortdog/img-4.jpg",
			"/images/hoteis/nortdog/img-5.jpg",
			"/images/hoteis/nortdog/img-6.jpeg",
			"/images/hoteis/nortdog/img-7.jpg",
			"/images/hoteis/nortdog/img-8.jpg",
		],
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
	},
	{
		uuid: "1a2b3c4d-0014-0014-0014-000000000014",
		name: "Family Dog",
		region: ["f0d2c8a9-5f7a-4e30-b8a4-d3b9a8f7e6c5"],
		address: "Rua do Bustelo 450, Alheira, Barcelos",
		location: "Barcelos",
		lat: 41.608884,
		lng: -8.551765,
		rating: 4,
		contact: "912376597",
		email: "geral@hotelfamilydog.pt",
		website: "https://hotelfamilydog.pt/",
		facebook: "https://www.facebook.com/hotelfamilydog/",
		instagram: "https://www.instagram.com/hotelfamilydog/",
		petabookPartner: false,
		shortDescription:
			"Family Dog oferece quartos autónomos e parques ao ar livre com atenção personalizada para o bem-estar dos cães.",
		longDescription:
			"O Hotel Family Dog, localizado em Alheira, Barcelos, destaca-se pela sua preocupação com o bem-estar e conforto dos cães hospedados. Oferece quartos autónomos com áreas interiores e exteriores privativas, higienizados diariamente. Com cinco mil metros quadrados de espaço, divididos em parques ao ar livre, arborizados e vedados, os cães têm acesso diário a atividades recreativas e exercícios. A equipa do hotel garante atenção personalizada às características individuais e necessidades específicas de cada cão, assegurando a melhor comodidade possível. Para quem deseja conhecer o local, o Hotel Family Dog está de portas abertas para visitas. Os serviços disponíveis incluem áreas de descanso privadas, vários parques para lazer, contacto com a natureza, atividades adequadas a cada cão e vigilância permanente. Para a admissão no hotel, é necessário um boletim de vacinação atualizado, desparasitação interna e externa válida, e a aceitação dos termos e condições do hotel. O horário de funcionamento é de segunda a sexta-feira, das 9h00 às 18h00, com horários específicos para check-in e check-out.",
		services: "Hotel canino",
		prices: 18,
		reservationEmail: null,
		responsableName: null,
		conditions: "",
		workingHours: "",
		images: [
			"/images/hoteis/family-dog/img-1.jpg",
			"/images/hoteis/family-dog/img-2.jpg",
			"/images/hoteis/family-dog/img-3.jpg",
			"/images/hoteis/family-dog/img-4.jpeg",
			"/images/hoteis/family-dog/img-5.jpg",
			"/images/hoteis/family-dog/img-6.jpeg",
			"/images/hoteis/family-dog/img-7.jpg",
		],
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
	},
	// Hotels from Arquipélagos:
	{
		uuid: "1a2b3c4d-0015-0015-0015-000000000015",
		name: "Dogtel",
		region: ["ea3f9a57-2c8b-40d8-8f51-7f9f8d8a27cb"],
		address: "Rua do Lazareto 227, São Gonçalo",
		location: "São Gonçalo",
		lat: 32.649031,
		lng: -16.880921,
		rating: 4,
		contact: "927206258",
		email: "geral@dogtel.pt",
		website: "https://www.dogtel.pt/",
		facebook: "https://www.facebook.com/Dogtel/?locale=pt_PT",
		instagram: "https://www.instagram.com/dogtel_school/",
		petabookPartner: true,
		shortDescription:
			"Dogtel oferece alojamento, treinos, creche e spa para cães e gatos em um espaço de 3000m².",
		longDescription:
			"O Dogtel é um complexo de excelência na Ilha da Madeira, dedicado ao bem-estar dos animais de estimação, que combina vários serviços num espaço de cerca de 3000m2. Este centro oferece uma gama completa de serviços, incluindo alojamento para cães e gatos, treinos caninos, uma piscina para hidroterapia e lazer, além de um spa para banhos e tosquias. Além disso, dispõem de um consultório veterinário, garantindo cuidados integrais de saúde e bem-estar para os pets. O Dogtel proporciona também serviços de creche canina, onde os cães podem interagir e socializar-se em um ambiente supervisionado enquanto seus donos estão ocupados. Outro destaque é o centro de reabilitação que utiliza a piscina para terapias, ajudando na recuperação de condições como artrites e lesões musculares.",
		services: "Hotel canino",
		prices: 0,
		reservationEmail: "Ricardojesus@dogtel.pt",
		responsableName: "",
		conditions: "",
		workingHours: "",
		images: [
			"/images/hoteis/dogtel/img-1.png",
			"/images/hoteis/dogtel/img-2.png",
			"/images/hoteis/dogtel/img-3.png",
			"/images/hoteis/dogtel/img-4.png",
			"/images/hoteis/dogtel/img-5.png",
			"/images/hoteis/dogtel/img-6.png",
		],
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
	},
	{
		uuid: "1a2b3c4d-0016-0016-0016-000000000016",
		name: "Clínica Veterinária São Miguel",
		region: ["ea3f9a57-2c8b-40d8-8f51-7f9f8d8a27cb"],
		address: "Rua das Mercês 29, Atalhada Lagoa",
		location: "Madeira",
		lat: 37.748071,
		lng: -25.592772,
		rating: 4,
		contact: "968066368",
		email: "geral@cvsm.pt",
		website: "https://www.cvsm.pt/#hotel",
		facebook: "https://www.facebook.com/ClinicaVeterinariaSaoMiguel/",
		instagram: null,
		petabookPartner: false,
		shortDescription:
			"Clínica Veterinária São Miguel dispõe de canis para cães e gatis para gatos, funcionando o ano todo.",
		longDescription:
			"O Hotel Canino é composto por 25 canis exteriores e 4 interiores, oferecendo maior conforto e comodidade para os animais. Criados a pensar no bem-estar dos cães, os canis exteriores têm 5 metros de comprimento por 2 metros de largura. O Hotel Felino dispõe de 21 gatis interiores. Oferecem um serviço personalizado de alimentação para atender às necessidades específicas de cada animal durante a estadia. O hotel está disponível durante os 365 dias do ano, com check-in e check-out efetuados no horário da clínica ou em outro horário a combinar, mediante disponibilidade. Para maior conveniência, também disponibilizam um serviço de domicílio para recolher e entregar os animais.",
		services: "Hotel canino",
		prices: 0,
		reservationEmail: null,
		responsableName: null,
		conditions: "",
		workingHours: "",
		images: [],
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
	},
	// Hotels from Algarve:
	{
		uuid: "1a2b3c4d-0017-0017-0017-000000000017",
		name: "Hotel do Cão Algarve",
		region: ["ae4d2c60-5f3f-4b2d-8e2d-7c2b8b6a9e42"],
		address: "Vale da Rainha, Estrada de Monchique, Portimão",
		location: "Portimão",
		lat: 37.219836,
		lng: -8.544594,
		rating: 4,
		contact: "963876246",
		email: "info@hoteldocao.pt",
		website: "https://www.hoteldocao.pt/",
		facebook: "https://www.facebook.com/hoteldocaoalgarve",
		instagram: "https://www.instagram.com/hoteldocao/",
		petabookPartner: false,
		shortDescription:
			"Hotel do Cão Algarve oferece alojamentos de luxo, praia para cães e SPA, com vigilância veterinária e transporte.",
		longDescription:
			"O Hotel do Cão Algarve oferece uma experiência única para cães e gatos, incluindo amplas áreas verdes, alojamentos de luxo com espaços interiores e exteriores, e uma equipa experiente para cuidar dos pets. Destaca-se pela oferta de uma praia onde os cães podem nadar e brincar, garantindo uma estadia inesquecível. As operações do hotel já duram mais de 10 anos e conta com um portfólio alargado de clientes satisfeitos. o Hotel garante um acompanhamento da saúde de todos os hóspedes através de uma vigilância veterinária constante. Os patudos também desfrutam de um SPA, onde a aparência, banho, escovagem e cortes de unhas são tratados. Também oferecem um serviço de transporte para evitar qualquer obstáculo para a estadia do seu cão.",
		services: "Hotel canino",
		prices: 0,
		reservationEmail: null,
		responsableName: null,
		conditions: "",
		workingHours: "",
		images: ["/images/hoteis/curti-dog/img-1.jpeg"],
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
	},
	{
		uuid: "1a2b3c4d-0018-0018-0018-000000000018",
		name: "Pets Inn",
		region: ["ae4d2c60-5f3f-4b2d-8e2d-7c2b8b6a9e42"],
		address: "Lugar da Renda, Loulé",
		location: "Loulé",
		lat: 37.146968,
		lng: -8.051465,
		rating: 4.7,
		contact: "915435823",
		email: "contacto@petsinn.pt",
		website: "https://petsinn.pt/",
		facebook: "https://www.facebook.com/petsinnalgarve/",
		instagram: "https://www.instagram.com/petsinn_algarve/",
		petabookPartner: true,
		shortDescription:
			"Pets Inn oferece um ambiente seguro e tranquilo para cães, gatos e outros animais com alojamento e creche canina.",
		longDescription:
			"Pets Inn é um hotel para animais de estimação que oferece um ambiente seguro, tranquilo e personalizado para cães, gatos e diversas outras espécies, como coelhos, répteis, furões e pássaros. Situado numa zona campestre, proporciona um refúgio relaxante, longe do stress da cidade, mas com fácil acesso urbano. Além do serviço de alojamento temporário, o Pets Inn também disponibiliza day care, uma creche canina ideal para donos com rotinas agitadas que querem garantir um dia estimulante e divertido para os seus animais. A infraestrutura foi pensada para criar uma experiência confortável, com um número reduzido de unidades de alojamento para garantir atenção individualizada. O espaço conta com capacidade para 13 cães, 18 gatos e 5 coelhos, além de áreas adaptadas para outros animais, incluindo répteis e aves. O objetivo do Pets Inn é proporcionar um ambiente onde todos os animais se sintam bem, relaxados e felizes, como se estivessem em casa.",
		services: "Hotel canino",
		prices: 20,
		reservationEmail: "geral@petsinn.pt",
		responsableName: "",
		conditions: "",
		workingHours: "",
		images: [
			"/images/hoteis/pets-inn/img-1.jpg",
			"/images/hoteis/pets-inn/img-10.jpg",
			"/images/hoteis/pets-inn/img-11.jpg",
			"/images/hoteis/pets-inn/img-12.jpg",
			"/images/hoteis/pets-inn/img-13.jpg",
			"/images/hoteis/pets-inn/img-14.jpg",
			"/images/hoteis/pets-inn/img-15.jpg",
			"/images/hoteis/pets-inn/img-16.jpg",
			"/images/hoteis/pets-inn/img-17.jpg",
		],
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
	},
	{
		uuid: "1a2b3c4d-0019-0019-0019-000000000019",
		name: "Dog Spa",
		region: ["ae4d2c60-5f3f-4b2d-8e2d-7c2b8b6a9e42"],
		address: "Monte Escrivão, Sítio da Igreja, Olhão",
		location: "Olhão",
		lat: 37.057183,
		lng: -7.866063,
		rating: 4.7,
		contact: "964639587",
		email: "info@dogspa.com.pt",
		website: "https://www.dogspa.pt/",
		facebook: "https://www.facebook.com/DogSpaQuintaLobos/",
		instagram: "https://www.instagram.com/dogspa_algarve/",
		petabookPartner: false,
		shortDescription:
			"Dog Spa oferece hotel, creche, tosquia, treinos e transporte para cães e gatos, com acompanhamento veterinário.",
		longDescription:
			"A Dog Spa em Olhão oferece uma ampla gama de serviços para cães e gatos, incluindo hotel, tosquia, creche, treinos, e serviço de transporte. As instalações são projetadas para garantir o melhor conforto e diversão para os animais, com boxes espaçosas e música ambiente para gatos. Uma equipa de profissionais da área veterinária assegura a saúde e bem-estar dos animais. O Hotel contém uma zona ampla, verde e vedada para que os animais possam brincar entre eles sem qualquer constrangimento. Enquanto usufruem desta área de brincadeira, os animais são devidamento acompanhados, a nivel individual, para que possam otimizar o bem-estar de cada um enquanto hóspedes do hotel.",
		services: "Hotel canino",
		prices: 0,
		reservationEmail: null,
		responsableName: "n.a.",
		conditions: "",
		workingHours: "",
		images: [
			"/images/hoteis/dog-spa/img-1.jpg",
			"/images/hoteis/dog-spa/img-2.jpg",
			"/images/hoteis/dog-spa/img-3.jpg",
			"/images/hoteis/dog-spa/img-4.jpg",
			"/images/hoteis/dog-spa/img-5.jpg",
			"/images/hoteis/dog-spa/img-6.jpg",
			"/images/hoteis/dog-spa/img-7.jpg",
			"/images/hoteis/dog-spa/img-8.jpg",
			"/images/hoteis/dog-spa/img-9.jpg",
		],
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
	},
	{
		uuid: "1a2b3c4d-0020-0020-0020-000000000020",
		name: "Centro Canino do Algarve",
		region: ["ae4d2c60-5f3f-4b2d-8e2d-7c2b8b6a9e42"],
		address: "Estrada municipal nr526 -962 A, Albufeira",
		location: "Albufeira",
		lat: 37.085988,
		lng: -8.287184,
		rating: 4.7,
		contact: "933925808",
		email: "centrocaninoalgarve@gmail.com",
		website: "https://www.facebook.com/CCAlgarve/?locale=pt_BR",
		facebook: "https://www.facebook.com/CCAlgarve/?locale=pt_BR",
		instagram: null,
		petabookPartner: false,
		shortDescription:
			"Centro Canino do Algarve oferece alojamento, passeios, treino e tosquias num ambiente rural com instalações modernas.",
		longDescription:
			"O Centro Canino do Algarve é um canil localizado em Albufeira, Portugal. O canil oferece uma variedade de serviços para cães, incluindo alojamento, alimentação, passeios, brincadeiras, treino, banhos e tosquias. O canil está localizado numa área rural, o que proporciona aos cães um ambiente tranquilo e relaxante. As instalações do canil são modernas e bem equipadas, com canis individuais, áreas de lazer e espaços exteriores para passeios. O pessoal do canil é experiente e qualificado, e está sempre disponível para cuidar dos cães com carinho e atenção. O canil oferece uma variedade de serviços personalizados, para que os tutores possam encontrar o que melhor se adequa às necessidades do seu animal.",
		services: "Hotel canino",
		prices: 0,
		reservationEmail: null,
		responsableName: null,
		conditions: "",
		workingHours: "",
		images: [
			"/images/hoteis/centro-canino-do-algarve/img-1.jpg",
			"/images/hoteis/centro-canino-do-algarve/img-2.jpg",
			"/images/hoteis/centro-canino-do-algarve/img-3.jpg",
			"/images/hoteis/centro-canino-do-algarve/img-4.jpg",
			"/images/hoteis/centro-canino-do-algarve/img-5.jpg",
		],
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
	},
	{
		uuid: "1a2b3c4d-0021-0021-0021-000000000021",
		name: "Pet Hotel do Algarve",
		region: ["ae4d2c60-5f3f-4b2d-8e2d-7c2b8b6a9e42"],
		address: "Caixa Postal 245-A, Faro",
		location: "Faro",
		lat: 37.125334,
		lng: -7.976966,
		rating: 4.8,
		contact: "960289169",
		email: "pethoteldoalgarve.lda@gmail.com",
		website: "https://www.pethoteldoalgarve.com/",
		facebook: "https://www.facebook.com/pethoteldoalgarve/?locale=pt_PT",
		instagram: "https://www.instagram.com/pet.hotel.do.algarve/",
		petabookPartner: true,
		shortDescription:
			"Pet Hotel do Algarve oferece suítes privativas isotérmicas, passeios diários e apoio veterinário, com transporte especializado.",
		longDescription:
			"O Merrylegs PET Hotel é um hotel familiar para animais que oferece alojamento de luxo, cuidado diário, treino para cães, e serviço de entrega e coleta. Está operacional há 12 anos e localiza-se num espaço construído de propósito para proporcionar um ambiente seguro e confortável para cães, gatos e pequenos animais. As infraestruturas do hotel incluem apartamentos caninos, que tencionam proporcionar um ambiente confortável, estável e calmo para o animal. Além disso, a equipa do hotel acredita que o exercício e cuidado diário são essenciais para promover uma boa estadia do animal no Merrylegs.",
		services: "Hotel canino",
		prices: 22,
		reservationEmail: "pethoteldoalgarve.lda@gmail.com",
		responsableName: "",
		conditions: "",
		workingHours: "",
		images: [
			"/images/hoteis/pet-hotel-do-algarve/img-1.jpg",
			"/images/hoteis/pet-hotel-do-algarve/img-10.jpg",
			"/images/hoteis/pet-hotel-do-algarve/img-12.jpg",
			"/images/hoteis/pet-hotel-do-algarve/img-6.jpg",
			"/images/hoteis/pet-hotel-do-algarve/img-8.jpg",
		],
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
	},
	{
		uuid: "1a2b3c4d-0022-0022-0022-000000000022",
		name: "Merrylegs Pet Hotel",
		region: ["ae4d2c60-5f3f-4b2d-8e2d-7c2b8b6a9e42"],
		address: "Sitio Estação Loulé 4 Estrada, Loulé",
		location: "Loulé",
		lat: 37.10439,
		lng: -8.059192,
		rating: 4,
		contact: "927296332",
		email: "merrylegspethotel@gmail.com",
		website: "https://www.merrylegspethotel.com/",
		facebook: "https://www.facebook.com/merrylegspethotel",
		instagram:
			"https://www.instagram.com/explore/locations/1019415244/merrylegs-pet-hotel/",
		petabookPartner: false,
		shortDescription:
			"Merrylegs Pet Hotel oferece alojamento de luxo, treino e transporte para cães, gatos e pequenos animais, com 12 anos de experiência.",
		longDescription:
			"O Merrylegs PET Hotel é um hotel familiar para animais que oferece alojamento de luxo, cuidado diário, treino para cães, e serviço de entrega e coleta. Está operacional há 12 anos e localiza-se num espaço construído de propósito para proporcionar um ambiente seguro e confortável para cães, gatos e pequenos animais. As infraestruturas do hotel incluem apartamentos caninos, que tencionam proporcionar um ambiente confortável, estável e calmo para o animal. Além disso, a equipa do hotel acredita que o exercício e cuidado diário são essenciais para promover uma boa estadia do animal no Merrylegs.",
		services: "Hotel canino",
		prices: 0,
		reservationEmail: null,
		responsableName: null,
		conditions: "",
		workingHours: "",
		images: [
			"/images/hoteis/merrylegs/img-1.png",
			"/images/hoteis/merrylegs/img-2.png",
			"/images/hoteis/merrylegs/img-3.jpg",
			"/images/hoteis/merrylegs/img-4.jpg",
			"/images/hoteis/merrylegs/img-5.jpg",
			"/images/hoteis/merrylegs/img-6.jpg",
		],
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
	},
	{
		uuid: "1a2b3c4d-0023-0023-0023-000000000023",
		name: "Herdade Bonanza",
		region: ["ae4d2c60-5f3f-4b2d-8e2d-7c2b8b6a9e42"],
		address: "Estrada da Barragem, Sitio da Moira 491, Lagos",
		location: "Lagos",
		lat: 37.159396,
		lng: -8.672303,
		rating: 4.9,
		contact: "967344230",
		email: "info@herdadebonanza.com",
		website: "https://www.herdadebonanza.com/",
		facebook: "https://www.facebook.com/hbonanzadogresort/",
		instagram: "https://www.instagram.com/hbonanzadogresort/",
		petabookPartner: false,
		shortDescription:
			"Herdade Bonanza é um resort canino em Lagos com alojamento, creche, treino e transporte, com suítes isoladas e piscina interior.",
		longDescription:
			"A Herdade Bonanza, situada em Lagos, é um resort canino que enfatiza o tratamento familiar para todos os cães. Oferece diversos serviços como alojamento, cuidados de higiene, uma equipa dedicada, creche, aulas de treino, e transporte para os animais. O Resort dispõe de 43 suítes privadas com uma dimensão de 9 m2 a 12 m2. Estas infraestruturas são revestidas com cortiça para garantir um isolamento térmico e sonoro.  Durante a estadia, o patudo terá acesso à piscina interior, preparada para cães de todos os portes, pavilhões de atividade com monitorização permanente da nossa equipa. A Herdade dispõe de vários campos vedados independentes, com água e sombra.",
		services: "Hotel canino",
		prices: 0,
		reservationEmail: null,
		responsableName: null,
		conditions: "",
		workingHours: "",
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
		images: [
			"/images/hoteis/herdade-bonanza/img-1.jpg",
			"/images/hoteis/herdade-bonanza/img-10.jpg",
			"/images/hoteis/herdade-bonanza/img-13.jpg",
			"/images/hoteis/herdade-bonanza/img-15.jpg",
			"/images/hoteis/herdade-bonanza/img-17.jpg",
			"/images/hoteis/herdade-bonanza/img-19.jpg",
			"/images/hoteis/herdade-bonanza/img-6.jpg",
			"/images/hoteis/herdade-bonanza/img-8.jpg",
		],
	},
	{
		uuid: "1a2b3c4d-0024-0024-0024-000000000024",
		name: "Curti Dog",
		region: ["ba9a11fa-3d9d-4d2b-90f8-6b987d0a2c34"],
		address: "Rua Casal da Curtinha 13 2530, Reguengo Grande",
		location: "Reguengo Grande",
		lat: 39.290556,
		lng: -9.226612,
		rating: 4.9,
		contact: "914819881",
		email: "curti_dog@hotmail.com",
		website: null,
		facebook: "https://www.facebook.com/CurtiDog18/?locale=pt_PT",
		instagram: "https://www.instagram.com/curti_dog/",
		petabookPartner: true,
		shortDescription:
			"A Curti Dog oferece hospedagem, creche e estética para cães e gatos, com serviços de petshop, adestramento e transporte.",
		longDescription:
			"A Curti Dog é uma empresa familiar que foi estabelecida em 2018 e está situada na zona oeste. Esta empresa oferece uma variedade de serviços para cães e gatos, incluindo hospedagem e creche. Durante o dia, os animais têm acesso a um espaço aberto, enquanto à noite, cada um é acomodado em uma box individual com sistemas de proteção contra frio, chuva e calor. Além das opções de hospedagem, a Curti Dog disponibiliza serviços de estética animal, que incluem tosquias, banhos e tratamentos para o pelo e a pele. A empresa também conta com uma petshop, oferece treinamentos de adestramento canino, transportes para consultas veterinárias e serviços de lavanderia. Para manter os donos informados e tranquilos, são realizadas publicações diárias com vídeos e fotos dos hóspedes.",
		services: "Hotel canino",
		prices: 10,
		reservationEmail: "curti_dog@hotmail.com",
		responsableName: "",
		conditions: "",
		workingHours: "",
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
		images: [
			"/images/hoteis/curti-dog/img-1.jpeg",
			"/images/hoteis/curti-dog/img-2.jpeg",
			"/images/hoteis/curti-dog/img-3.jpeg",
			"/images/hoteis/curti-dog/img-4.jpeg",
			"/images/hoteis/curti-dog/img-5.jpeg",
			"/images/hoteis/curti-dog/img-6.jpeg",
		],
	},
	{
		uuid: "1a2b3c4d-0025-0025-0025-000000000025",
		name: "Hotel e Spa Animal VIP",
		region: ["ba9a11fa-3d9d-4d2b-90f8-6b987d0a2c34"],
		address: "Rua da Escola 16, Travassós de Baixo, Viseu",
		location: "Viseu",
		lat: 40.679537,
		lng: -7.883873,
		rating: 4.5,
		contact: "924442759",
		email: "animalvip@ivcevidensia.pt",
		website: "https://www.animalvip.pt/hotel-spa/",
		facebook: "https://www.facebook.com/centroveterinario.beiraalta",
		instagram: "https://www.instagram.com/Animal_vip/",
		petabookPartner: false,
		shortDescription:
			"O Hotel e SPA Animal VIP oferece suites de luxo para cães e gatos com TV, webcam e videochamadas diárias, além de serviços de piscina, grooming e massagens.",
		longDescription:
			"O Hotel e SPA Animal VIP, localizado em Travassós de Baixo, Viseu, oferece uma experiência de luxo para cães e gatos, ultrapassando o conceito tradicional de hotel para animais. Os animais podem desfrutar de suites de luxo com áreas internas e externas, equipadas com televisão, ventoinha e webcam com transmissão para o smartphone do dono. As estadias incluem passeios diários em um parque vedado de 4000m² e videochamadas com os donos ao fim do dia. Para os gatos, há jardins de inverno e verão e todas as suites têm janela para a rua. O hotel também oferece serviços de grooming diário, massagens, e outros mimos. Além das comodidades de luxo, o Hotel e SPA Animal VIP disponibiliza uma série de serviços adicionais, como piscina no terraço, câmaras de videovigilância, banhos e tosquias, videografia, táxi para animais e massagens. Localizado na Estrada entre Viseu e Sátão, junto ao antigo nó da IP5, o hotel funciona de segunda a sábado, das 10h00 às 12h00 e das 15h00 às 19h00. As reservas podem ser feitas online ou via telefone, proporcionando uma estadia inesquecível para os animais, que podem até relutar em voltar para casa após a experiência.",
		services: "Hotel canino",
		prices: 0,
		reservationEmail: null,
		responsableName: null,
		conditions: "",
		workingHours: "",
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
		images: [
			"/images/hoteis/hotel-e-spa-animal-vip/img-1.png",
			"/images/hoteis/hotel-e-spa-animal-vip/img-10.jpg",
			"/images/hoteis/hotel-e-spa-animal-vip/img-11.jpg",
			"/images/hoteis/hotel-e-spa-animal-vip/img-12.jpg",
			"/images/hoteis/hotel-e-spa-animal-vip/img-2.jpg",
			"/images/hoteis/hotel-e-spa-animal-vip/img-5.png",
		],
	},
	{
		uuid: "1a2b3c4d-0026-0026-0026-000000000026",
		name: "Trela Amarela",
		region: ["ba9a11fa-3d9d-4d2b-90f8-6b987d0a2c34"],
		address: "Rua da Folha 35, Santarém",
		location: "Santarém",
		lat: 39.25506,
		lng: -8.754333,
		rating: 5,
		contact: "938503142",
		email: null,
		website: "https://trelaamarela.pt/pet-hotel/",
		facebook: "https://www.facebook.com/Trela.Amarela/?locale=pt_PT",
		instagram: "https://www.instagram.com/atrelaamarela/",
		petabookPartner: false,
		shortDescription:
			"O Hotel d’A Trela Amarela oferece alojamento para cães e gatos com amplos espaços vedados, passeios diários e monitorização veterinária.",
		longDescription:
			"Situado numa zona rural, apenas a 5 minutos da saída da A1 em Santarém, o Hotel d’A Trela Amarela dispõe de 20 boxes para cães e 10 boxes para gatos. Os cães desfrutam de dois passeios diários em um espaço vedado de 15.000 m², onde podem correr livremente, enquanto suas brincadeiras são filmadas e fotografadas para envio aos donos. Em caso de doença súbita, o médico veterinário responsável observa os hóspedes, sendo os custos suportados pelos donos. Brinquedos e objetos familiares são bem-vindos para facilitar a adaptação dos animais. Os check-ins e check-outs são realizados das 9h às 11h e das 16h às 18h.",
		services: "Hotel canino",
		prices: 14,
		reservationEmail: null,
		responsableName: null,
		conditions: "",
		workingHours: "",
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
		images: [
			"/images/hoteis/trela-amarela/img-1.jpg",
			"/images/hoteis/trela-amarela/img-10.jpg",
			"/images/hoteis/trela-amarela/img-11.jpg",
			"/images/hoteis/trela-amarela/img-12.jpg",
			"/images/hoteis/trela-amarela/img-13.jpg",
			"/images/hoteis/trela-amarela/img-14.jpg",
			"/images/hoteis/trela-amarela/img-15.jpg",
		],
	},
	// Hotels from Alentejo:
	{
		uuid: "1a2b3c4d-0027-0027-0027-000000000027",
		name: "Monte da Benviuda",
		region: ["d1a5a76f-7a8f-4b92-9a3f-abc1d1e2f345"],
		address: "Monte da Benviuda, Alcaria Ruiva, Mértola",
		location: "Mértola",
		lat: 37.711814,
		lng: -7.8394,
		rating: 4.7,
		contact: "963187118",
		email: "canilmontedabenviuda.blogspot.pt",
		website: null,
		facebook:
			"https://www.facebook.com/p/Canil-Monte-da-Benviuda-100063803253210/",
		instagram: "https://www.instagram.com/canil.monte.da.benviuda/",
		petabookPartner: true,
		shortDescription:
			"Monte da Benviuda oferece alojamento tranquilo para cães com boxes individuais, parque de passeios e centro de estética canina.",
		longDescription:
			'O Hotel Canino "Monte da Benviúda", localizado no concelho de Mértola, terá o maior prazer em alojar o seu cão em caso de necessidade de sair, comprometendo-se a proporcionar um tratamento personalizado cheio de dedicação e carinho, num ambiente acolhedor na tranquilidade do Alentejo. O seu animal terá espaço para correr e brincar, podendo fazer novos amigos de quatro patas, essencial para o seu equilíbrio social.  O Hotel dispõe de boxes individuais, parque de passeios e um centro de estética Canina.',
		services: "Hotel canino",
		prices: 12,
		reservationEmail: "Monte.da.benviuda@sapo.pt",
		responsableName: "",
		conditions: "",
		workingHours: "",
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
		images: [
			"/images/hoteis/monte-da-benviuda/img-1.jpg",
			"/images/hoteis/monte-da-benviuda/img-10.jpg",
			"/images/hoteis/monte-da-benviuda/img-11.jpg",
			"/images/hoteis/monte-da-benviuda/img-12.jpg",
			"/images/hoteis/monte-da-benviuda/img-13.jpg",
			"/images/hoteis/monte-da-benviuda/img-2.jpg",
			"/images/hoteis/monte-da-benviuda/img-3.jpg",
			"/images/hoteis/monte-da-benviuda/img-4.jpg",
			"/images/hoteis/monte-da-benviuda/img-5.jpg",
			"/images/hoteis/monte-da-benviuda/img-6.jpg",
			"/images/hoteis/monte-da-benviuda/img-7.jpg",
			"/images/hoteis/monte-da-benviuda/img-8.jpg",
			"/images/hoteis/monte-da-benviuda/img-9.jpg",
		],
	},
	{
		uuid: "1a2b3c4d-0028-0028-0028-000000000028",
		name: "Residência Canina e Felina",
		region: ["d1a5a76f-7a8f-4b92-9a3f-abc1d1e2f345"],
		address: "Fonte Santa Estrada da Calçadinha, CP 219, Elvas",
		location: "Elvas",
		lat: 38.88296,
		lng: -7.19067,
		rating: 4.7,
		contact: "268622607",
		email: "geral.pethotel@fortedelvas.pt",
		website: "https://www.residenciacanina.pt/pt/canina.php",
		facebook:
			"https://www.facebook.com/residenciacaninafortedelvas/?locale=pt_PT",
		instagram: "https://www.instagram.com/residenciacaninafelina/",
		petabookPartner: false,
		shortDescription:
			"Residência Canina e Felina Forte de Elvas oferece alojamento seguro para cães e gatos, com treinos e cuidados veterinários.",
		longDescription:
			"A Residência Canina e Felina Forte de Elvas é um local dedicado ao cuidado e bem-estar dos amigos de quatro patas. Localizada em Elvas, esta residência oferece um ambiente seguro e confortável para cães e gatos, proporcionando serviços de hospedagem, cuidados diários e atividades recreativas. A equipa, composta por profissionais qualificados e amantes de animais, garante que todos os hóspedes recebam atenção personalizada e cuidados adequados às suas necessidades específicas. Além dos serviços de hospedagem, a Residência Canina e Felina Forte de Elvas também oferece treinos e serviços veterinários, assegurando que os animais estejam sempre saudáveis e bem cuidados. Com instalações modernas e espaços amplos para brincadeiras e exercícios, esta residência é o lugar ideal para deixar os animais de estimação, seja durante uma viagem ou por um período de tempo prolongado. Aqui, os cães e gatos encontram um verdadeiro lar longe de casa, onde podem desfrutar de carinho, segurança e diversão.",
		services: "Hotel canino",
		prices: 12,
		reservationEmail: null,
		responsableName: null,
		conditions: "",
		workingHours: "",
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
		images: [
			"/images/hoteis/residencia-canina-e-felina/img-1.jpg",
			"/images/hoteis/residencia-canina-e-felina/img-10.jpg",
			"/images/hoteis/residencia-canina-e-felina/img-11.jpg",
			"/images/hoteis/residencia-canina-e-felina/img-12.jpg",
		],
	},
];

// Build an object keyed by the hotel uuid for easy lookup.
export const hotelObj: HotelData = hotelList.reduce((acc, hotel) => {
	acc[hotel.uuid] = hotel;
	return acc;
}, {} as HotelData);
