// hotels.ts

// Define the Hotel interface using camelCase naming conventions.
// The region property is now an array of region UUID strings.
export interface Hotel {
	uuid: string;
	name: string | null;
	region: string[] | null; // now an array of region UUIDs
	address: string | null;
	location: string | null;
	lat: number | null;
	lng: number | null;
	rating: number | null;
	contact: string | null; // storing phone numbers as strings
	email: string | null;
	website: string | null;
	facebook: string | null;
	instagram: string | null;
	petabookPartner: boolean; // converted to boolean
	shortDescription: string | null;
	longDescription: string | null;
	services: string | null;
	prices: number | null;
	reservationEmail: string | null;
	responsableName: string | null;
	conditions: string | null;
	workingHours: string | null;
	images: string[] | null;
	checkInHours: string | null;
	checkOutHours: string | null;
	checkInDays: string | null;
	checkOutDays: string | null;
	restrictions: string | null;
	gps?: {
		lat: number;
		lng: number;
	};
}

// A mapping type to index hotels by their uuid .
export interface HotelData {
	[uuid: string]: Hotel;
}

/*
  Region IDs (from your regionList):
    - Lisboa:      "c5d53de2-15e5-4fa8-a0f3-9c4b30b18a91"
    - Centro:      "ba9a11fa-3d9d-4d2b-90f8-6b987d0a2c34"
    - Porto:       "6e3c11f3-3a28-4e2b-bf9e-6713c45b0a6a"
    - Norte:       "f0d2c8a9-5f7a-4e30-b8a4-d3b9a8f7e6c5"
    - Arquipélagos:"ea3f9a57-2c8b-40d8-8f51-7f9f8d8a27cb"
    - Algarve:     "ae4d2c60-5f3f-4b2d-8e2d-7c2b8b6a9e42"
    - Alentejo:    "d1a5a76f-7a8f-4b92-9a3f-abc1d1e2f345"
*/

// The hotel list – note that "n.a." values have been converted to null.
// The region property is now an array of region UUIDs.
// For hotels originally from Lisbon, we add both "Lisboa" and "Centro".
// For hotels originally from Porto, we add both "Porto" and "Norte".
export const hotelList: Hotel[] = [
	// Hotels from Lisbon:
	{
		uuid: "1a2b3c4d-0001-0001-0001-000000000001",
		name: "Quinta da Patada",
		region: [
			"c5d53de2-15e5-4fa8-a0f3-9c4b30b18a91", // Lisboa
			"ba9a11fa-3d9d-4d2b-90f8-6b987d0a2c34", // Centro
		],
		address:
			"Rua do Murtal, Quinta da Patada Manjoeira, 2660-499 Santo Antão do Tojal",
		location: "Lisbon",
		lat: 38.876809,
		lng: -9.159942,
		rating: 4,
		contact: "912385650",
		email: "geral@quintadapatada.com",
		website: "https://quintadapatada.com/",
		facebook: "https://www.facebook.com/quintadapatada/",
		instagram: "https://www.instagram.com/quintadapatada/",
		petabookPartner: true,
		shortDescription:
			"A Quinta da Patada, em Loures, é um hotel para cães com hospedagem, creche e banhos, oferecendo supervisão 24 horas.",
		longDescription:
			"A Quinta da Patada, localizada em Santo Antão do Tojal, Loures, oferece hospedagem, creche, banhos e tosquias, com 25 boxes individuais e atividades ao ar livre, garantindo conforto e segurança aos hóspedes.",
		services: "Hotel canino",
		prices: 17,
		reservationEmail: "geral@quintadapatada.com",
		responsableName: "",
		conditions: "",
		workingHours: "",
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
		images: [
			"/images/hoteis/quinta-da-patada/img-1.jpeg",
			"/images/hoteis/quinta-da-patada/img-10.jpeg",
			"/images/hoteis/quinta-da-patada/img-11.jpeg",
			"/images/hoteis/quinta-da-patada/img-12.jpeg",
			"/images/hoteis/quinta-da-patada/img-13.jpeg",
		],
	},
	{
		uuid: "1a2b3c4d-0002-0002-0002-000000000002",
		name: "Just4Buddies",
		region: [
			"c5d53de2-15e5-4fa8-a0f3-9c4b30b18a91",
			"ba9a11fa-3d9d-4d2b-90f8-6b987d0a2c34",
		],
		address: "Praceta Damião Peres 25, São Domingos de Rana",
		location: "Lisbon",
		lat: 38.710714,
		lng: -9.348297,
		rating: 4,
		contact: "911128070",
		email: "geral@just4buddies.pt",
		website: "https://just4buddies.pt/",
		facebook: "https://www.facebook.com/just4buddies?locale=pt_BR",
		instagram: "https://www.instagram.com/just4buddies/",
		petabookPartner: true,
		shortDescription:
			"A creche canina em Cascais garante dias felizes e estimulantes para os patudos.",
		longDescription:
			"A creche canina de Just4Buddies em Cascais proporciona um ambiente seguro e carinhoso, com loja e treinadora, enquanto os donos estão ausentes.",
		services: "Hotel canino",
		prices: 18,
		reservationEmail: "geral@just4buddies.pt",
		responsableName: "",
		conditions: "",
		workingHours: "",
		images: [
			"/images/hoteis/just4buddies/img-1.jpg",
			"/images/hoteis/just4buddies/img-2.jpg",
			"/images/hoteis/just4buddies/img-3.jpg",
			"/images/hoteis/just4buddies/img-4.jpg",
			"/images/hoteis/just4buddies/img-5.jpg",
		],
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
	},
	{
		uuid: "1a2b3c4d-0003-0003-0003-000000000003",
		name: "Recreio Canino",
		region: [
			"c5d53de2-15e5-4fa8-a0f3-9c4b30b18a91",
			"ba9a11fa-3d9d-4d2b-90f8-6b987d0a2c34",
		],
		address: "Rua da Amoreira, Lousa",
		location: "Lisbon",
		lat: 38.894309,
		lng: -9.205765,
		rating: 4,
		contact: "210963508",
		email: "info@recreiocanino.com",
		website: "https://recreiocanino.com/",
		facebook: "https://www.facebook.com/RecreioCanino/?locale=pt_PT",
		instagram: "https://www.instagram.com/recreiocanino/",
		petabookPartner: false,
		shortDescription:
			"Recreio Canino promove socialização e bem-estar dos cães com serviços personalizados.",
		longDescription:
			"Recreio Canino oferece um ambiente seguro e estimulante para os cães, funcionando de segunda a sexta das 9h às 16h, com serviços adaptados às necessidades dos animais.",
		services: "Hotel canino",
		prices: 25,
		reservationEmail: null,
		responsableName: null,
		conditions: "",
		workingHours: "",
		images: [
			"/images/hoteis/recreio-canino/img-1.jpg",
			"/images/hoteis/recreio-canino/img-10.jpg",
			"/images/hoteis/recreio-canino/img-11.jpg",
			"/images/hoteis/recreio-canino/img-12.jpg",
			"/images/hoteis/recreio-canino/img-13.jpg",
			"/images/hoteis/recreio-canino/img-14.jpg",
		],
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
	},
	{
		uuid: "1a2b3c4d-0004-0004-0004-000000000004",
		name: "101 Hotel Canino",
		region: [
			"c5d53de2-15e5-4fa8-a0f3-9c4b30b18a91",
			"ba9a11fa-3d9d-4d2b-90f8-6b987d0a2c34",
		],
		address: "Quinta do Pinheirinho, R. dos Comerciantes, Pinhal Novo",
		location: "Pinhal Novo, Setubal",
		lat: 38.624182,
		lng: -8.871338,
		rating: 4,
		contact: "913847150",
		email: "101hotelcanino@gmail.com",
		website: "https://www.banhosetosquiasaodomicilio.pt/hotel-canino",
		facebook:
			"https://www.facebook.com/p/101-Servi%C3%A7os-para-C%C3%A3es-e-Gatos-ao-Domic%C3%ADlio-100063469993660/?locale=pt_BR",
		instagram: "https://www.instagram.com/101servicos/",
		petabookPartner: true,
		shortDescription:
			"O Hotel Canino 101 oferece instalações modernas com boxes privadas e parques espaçosos.",
		longDescription:
			"Localizado numa zona tranquila do Pinhal Novo, o Hotel Canino 101 dispõe de 20 boxes privadas e amplos parques com áreas equipadas para a socialização dos cães. Oferece serviços de banho e transporte, permitindo aos donos acompanhar a estadia por vídeos.",
		services: "Hotel canino",
		prices: 12,
		reservationEmail: "101hotelcanino@gmail.com",
		responsableName: "",
		conditions: "",
		workingHours: "",
		images: [
			"/images/hoteis/hotel-101/img-1.jpg",
			"/images/hoteis/hotel-101/img-10.jpeg",
			"/images/hoteis/hotel-101/img-11.jpeg",
			"/images/hoteis/hotel-101/img-12.jpeg",
			"/images/hoteis/hotel-101/img-13.jpeg",
			"/images/hoteis/hotel-101/img-14.jpeg",
			"/images/hoteis/hotel-101/img-15.jpeg",
			"/images/hoteis/hotel-101/img-16.jpeg",
			"/images/hoteis/hotel-101/img-17.jpeg",
			"/images/hoteis/hotel-101/img-18.jpeg",
			"/images/hoteis/hotel-101/img-19.jpeg",
			"/images/hoteis/hotel-101/img-2.jpg",
			"/images/hoteis/hotel-101/img-20.jpeg",
			"/images/hoteis/hotel-101/img-21.jpeg",
			"/images/hoteis/hotel-101/img-22.jpeg",
			"/images/hoteis/hotel-101/img-3.jpg",
			"/images/hoteis/hotel-101/img-4.jpg",
			"/images/hoteis/hotel-101/img-5.jpg",
			"/images/hoteis/hotel-101/img-6.jpg",
			"/images/hoteis/hotel-101/img-7.jpg",
			"/images/hoteis/hotel-101/img-8.jpg",
			"/images/hoteis/hotel-101/img-9.jpg",
		],
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
	},
	{
		uuid: "1a2b3c4d-0005-0005-0005-000000000005",
		name: "Curti Dog",
		region: [
			"c5d53de2-15e5-4fa8-a0f3-9c4b30b18a91",
			"ba9a11fa-3d9d-4d2b-90f8-6b987d0a2c34",
		],
		address: "Rua Casal da Curtinha 13 2530, Reguengo Grande",
		location: "Pinhal Novo, Setubal",
		lat: 39.290316,
		lng: -9.226053,
		rating: 4,
		contact: "914819881",
		email: "curti_dog@hotmail.com",
		website: null,
		facebook: "https://www.facebook.com/CurtiDog18/?locale=pt_PT",
		instagram: "https://www.instagram.com/curti_dog/",
		petabookPartner: true,
		shortDescription:
			"A Curti Dog oferece hospedagem, creche e estética para cães e gatos, com serviços de petshop, adestramento e transporte.",
		longDescription:
			"Estabelecida em 2018, a Curti Dog é uma empresa familiar que oferece serviços variados para cães e gatos, incluindo hospedagem, creche e estética. Durante o dia, os animais têm acesso a um espaço aberto, enquanto à noite são acomodados em boxes individuais com proteção contra condições climáticas adversas. Também oferece serviços de adestramento e transporte para consultas veterinárias.",
		services: "Hotel canino",
		prices: 10,
		reservationEmail: "curti_dog@hotmail.com",
		responsableName: "",
		conditions: "",
		workingHours: "",
		images: [
			"/images/hoteis/curti-dog/img-1.jpeg",
			"/images/hoteis/curti-dog/img-2.jpeg",
			"/images/hoteis/curti-dog/img-3.jpeg",
			"/images/hoteis/curti-dog/img-4.jpeg",
			"/images/hoteis/curti-dog/img-5.jpeg",
			"/images/hoteis/curti-dog/img-6.jpeg",
		],
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
	},
	{
		uuid: "1a2b3c4d-0006-0006-0006-000000000006",
		name: "Sweetpet",
		location: "Lisboa",
		lat: 38.716445,
		lng: -9.272457,
		rating: 4,
		region: [
			"c5d53de2-15e5-4fa8-a0f3-9c4b30b18a91",
			"ba9a11fa-3d9d-4d2b-90f8-6b987d0a2c34",
		],
		address: "Caminho das Batatas nº 2, Queijas",
		contact: "912269890",
		email: "info@sweetpet.pt",
		website: "https://www.sweetpet.pt/",
		facebook: "https://www.facebook.com/sweetpetcascais/?locale=pt_PT",
		instagram: "https://www.instagram.com/sweetpet/",
		petabookPartner: false,
		shortDescription:
			"Sweetpet oferece um ambiente holístico para o bem-estar canino com serviços de saúde, educação e socialização.",
		longDescription:
			"Situada em Queijas, a Sweetpet adota uma abordagem holística no cuidado dos cães, tratando-os como membros da família. Suas instalações, que se estendem por 9.000 m², incluem parques, piscina e um chalet, e oferecem programas personalizados de saúde e educação canina.",
		services: "Hotel canino",
		prices: 20,
		reservationEmail: null,
		responsableName: null,
		conditions: "",
		workingHours: "",
		images: [
			"/images/hoteis/sweetpet/img-1.jpg",
			"/images/hoteis/sweetpet/img-2.jpg",
			"/images/hoteis/sweetpet/img-3.jpg",
			"/images/hoteis/sweetpet/img-4.jpg",
			"/images/hoteis/sweetpet/img-5.jpg",
			"/images/hoteis/sweetpet/img-6.jpg",
			"/images/hoteis/sweetpet/img-7.jpg",
		],
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
	},
	// Hotels from Porto:
	{
		uuid: "1a2b3c4d-0009-0009-0009-000000000009",
		name: "Pet Hotel Gaia",
		region: [
			"6e3c11f3-3a28-4e2b-bf9e-6713c45b0a6a", // Porto
			"f0d2c8a9-5f7a-4e30-b8a4-d3b9a8f7e6c5", // Norte
		],
		address: "Rua Mata 798, Vila Nova de Gaia",
		location: "Vila Nova de Gaia, Porto",
		lat: 41.107207,
		lng: -8.570766,
		rating: 4,
		contact: "227840230",
		email: null,
		website: "https://pethotelgaia.com/",
		facebook: "https://www.facebook.com/pethotelgaia/?locale=pt_PT",
		instagram: "https://www.instagram.com/pet.hotel.gaia/",
		petabookPartner: false,
		shortDescription:
			"Pet Hotel Gaia oferece alojamento para cães e gatos com passeios diários e apoio veterinário, com opções de estadia Outdoor e Indoor.",
		longDescription:
			"Localizado em Vila Nova de Gaia, o Pet Hotel Gaia oferece alojamento para cães e gatos, dividido em estadias Outdoor para cães de médio/grande porte e Indoor para cães pequenos, com serviços de água fresca, cama confortável, passeios diários e apoio veterinário.",
		services: "Hotel canino",
		prices: 16,
		reservationEmail: null,
		responsableName: null,
		conditions: "",
		workingHours: "",
		images: [
			"/images/hoteis/pet-hotel-gaia/img-1.jpg",
			"/images/hoteis/pet-hotel-gaia/img-10.jpg",
			"/images/hoteis/pet-hotel-gaia/img-11.jpg",
			"/images/hoteis/pet-hotel-gaia/img-12.jpeg",
			"/images/hoteis/pet-hotel-gaia/img-13.jpeg",
			"/images/hoteis/pet-hotel-gaia/img-3.png",
			"/images/hoteis/pet-hotel-gaia/img-8.jpg",
			"/images/hoteis/pet-hotel-gaia/img-9.jpg",
		],
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
	},
	{
		uuid: "1a2b3c4d-0010-0010-0010-000000000010",
		name: "Domi Canis Cattus EcoHotel",
		region: [
			"6e3c11f3-3a28-4e2b-bf9e-6713c45b0a6a",
			"f0d2c8a9-5f7a-4e30-b8a4-d3b9a8f7e6c5",
		],
		address: "Rua da Cunha 140, Parada, Vila do Conde",
		location: "Vila do Conde",
		lat: 41.362698,
		lng: -8.645343,
		rating: 4,
		contact: "913274697",
		email: "domicaniscattus@gmail.com",
		website: null,
		facebook: "https://www.facebook.com/Ruicosta2016/?locale=pt_PT",
		instagram: "https://www.instagram.com/dcc_domi_canis_cattus/",
		petabookPartner: true,
		shortDescription:
			"O Domi Canis Cattus EcoHotel combina design inovador e conforto para animais, sendo premiado e reconhecido internacionalmente.",
		longDescription:
			"Concebido em 2015 e inaugurado em 2019, o Domi Canis Cattus EcoHotel, no distrito do Porto, se consolidou como um dos espaços mais inovadores na hospitalidade para animais, com prêmios como 5 Estrelas Regiões 2020 e reconhecimentos internacionais. Sua infraestrutura de vanguarda oferece um ambiente seguro e funcional para os hóspedes de quatro patas.",
		services: "Hotel canino",
		prices: 25,
		reservationEmail: "domicaniscattus@gmail.com",
		responsableName: "",
		conditions: "",
		workingHours: "",
		images: [
			"/images/hoteis/domi-cannis-catus/img-1.jpg",
			"/images/hoteis/domi-cannis-catus/img-10.jpg",
			"/images/hoteis/domi-cannis-catus/img-11.jpg",
		],
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
	},
	{
		uuid: "1a2b3c4d-0011-0011-0011-000000000011",
		name: "Pet Home",
		region: [
			"6e3c11f3-3a28-4e2b-bf9e-6713c45b0a6a",
			"f0d2c8a9-5f7a-4e30-b8a4-d3b9a8f7e6c5",
		],
		address: "Zona Industrial Arcos de Sadrão 401, Vila Nova de Gaia",
		location: "Pinhal Novo, Setubal",
		lat: 41.116894,
		lng: -8.580968,
		rating: 4,
		contact: "935094048",
		email: "geral.pet.home@gmail.com",
		website: "https://pethomept.wixsite.com/pethome",
		facebook: "https://pethomept.wixsite.com/pethome",
		instagram: "https://www.instagram.com/_pet.home_/",
		petabookPartner: false,
		shortDescription:
			"A Pet Home foi criada por enfermeiras veterinárias e educadoras caninas, oferecendo hotel, creche, treino e serviços estéticos.",
		longDescription:
			"Localizada na Zona Industrial dos Arcos de Sardão em Vila Nova de Gaia, a Pet Home oferece serviços de treino, consultas, creche e hotel para animais, com cada pet tendo direito a uma box individual e os donos acompanhando a estadia via redes sociais.",
		services: "Hotel canino",
		prices: 0,
		reservationEmail: null,
		responsableName: null,
		conditions: "",
		workingHours: "",
		images: [
			"/images/hoteis/pet-home/2nd-try/img-1.jpg",
			"/images/hoteis/pet-home/2nd-try/img-2.jpg",
			"/images/hoteis/pet-home/2nd-try/img-3.jpg",
			"/images/hoteis/pet-home/2nd-try/img-4.jpg",
			"/images/hoteis/pet-home/2nd-try/img-5.jpg",
			"/images/hoteis/pet-home/2nd-try/img-6.jpg",
			"/images/hoteis/pet-home/2nd-try/img-7.jpg",
		],
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
	},
	{
		uuid: "1a2b3c4d-0012-0012-0012-000000000012",
		name: "Pets and Family",
		region: [
			"6e3c11f3-3a28-4e2b-bf9e-6713c45b0a6a",
			"f0d2c8a9-5f7a-4e30-b8a4-d3b9a8f7e6c5",
		],
		address: "Rua Nova do Arquinho 426, Maia",
		location: "Maia",
		lat: 41.207731,
		lng: -8.600419,
		rating: 4,
		contact: "912741229",
		email: null,
		website: "https://petsandfamily.pt/",
		facebook: "https://www.facebook.com/petsandfamilypt/?locale=pt_BR",
		instagram: "https://www.instagram.com/pets.and.family/",
		petabookPartner: false,
		shortDescription:
			"Pets and Family oferece creche e hotel canino sem espaços confinados, com avaliação inicial para segurança e adaptação.",
		longDescription:
			"Localizada na Maia, Pets and Family oferece um serviço diferenciado de creche e hotel para cães, funcionando das 8h às 20h, sem espaços confinados e com atenção 24 horas, com descontos variáveis conforme o número de cães e fidelidade ao serviço.",
		services: "Hotel canino",
		prices: 19,
		reservationEmail: null,
		responsableName: null,
		conditions: "",
		workingHours: "",
		images: [
			"/images/hoteis/pets-and-family/img-1.jpg",
			"/images/hoteis/pets-and-family/img-2.jpg",
			"/images/hoteis/pets-and-family/img-3.jpg",
			"/images/hoteis/pets-and-family/img-4.jpg",
		],
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
	},
	// Hotels from Norte (already have region "Norte")
	{
		uuid: "1a2b3c4d-0013-0013-0013-000000000013",
		name: "Nortdog",
		region: ["f0d2c8a9-5f7a-4e30-b8a4-d3b9a8f7e6c5"],
		address: "Avenida de Santo André, nº 163, Braga",
		location: "Braga",
		lat: 41.541679,
		lng: -8.453439,
		rating: 4,
		contact: "965070933",
		email: "geral@nortdog.pt",
		website: "https://nortdog.pt/",
		facebook: "https://www.facebook.com/nortdogbraga/?locale=pt_PT",
		instagram: "https://www.instagram.com/nortdog_petinnature/",
		petabookPartner: false,
		shortDescription:
			"Nortdog, com 25 anos de experiência, oferece hotel, creche e treino para cães e gatos, com eventos solidários.",
		longDescription:
			"A Nortdog é uma academia para cães e gatos em Braga, com 25 anos de experiência, oferecendo uma ampla seleção de produtos e serviços, incluindo hotéis, creches e cursos de obediência. Também organiza eventos como a 'Aqua Dog Party', destinando parte das receitas a associações de proteção animal.",
		services: "Hotel canino",
		prices: 16,
		reservationEmail: null,
		responsableName: null,
		conditions: "",
		workingHours: "",
		images: [
			"/images/hoteis/nortdog/img-1.jpg",
			"/images/hoteis/nortdog/img-2.jpg",
			"/images/hoteis/nortdog/img-3.jpg",
			"/images/hoteis/nortdog/img-4.jpg",
			"/images/hoteis/nortdog/img-5.jpg",
			"/images/hoteis/nortdog/img-6.jpeg",
			"/images/hoteis/nortdog/img-7.jpg",
			"/images/hoteis/nortdog/img-8.jpg",
		],
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
	},
	{
		uuid: "1a2b3c4d-0014-0014-0014-000000000014",
		name: "Family Dog",
		region: ["f0d2c8a9-5f7a-4e30-b8a4-d3b9a8f7e6c5"],
		address: "Rua do Bustelo 450, Alheira, Barcelos",
		location: "Barcelos",
		lat: 41.608884,
		lng: -8.551765,
		rating: 4,
		contact: "912376597",
		email: "geral@hotelfamilydog.pt",
		website: "https://hotelfamilydog.pt/",
		facebook: "https://www.facebook.com/hotelfamilydog/",
		instagram: "https://www.instagram.com/hotelfamilydog/",
		petabookPartner: false,
		shortDescription:
			"Family Dog oferece quartos autónomos e parques ao ar livre com atenção personalizada para o bem-estar dos cães.",
		longDescription:
			"Localizado em Alheira, Barcelos, o Hotel Family Dog destaca-se pelo cuidado e conforto oferecidos aos cães, com quartos autónomos, amplos parques para recreação e atendimento personalizado, funcionando de segunda a sexta, das 9h às 18h.",
		services: "Hotel canino",
		prices: 18,
		reservationEmail: null,
		responsableName: null,
		conditions: "",
		workingHours: "",
		images: [
			"/images/hoteis/family-dog/img-1.jpg",
			"/images/hoteis/family-dog/img-2.jpg",
			"/images/hoteis/family-dog/img-3.jpg",
			"/images/hoteis/family-dog/img-4.jpeg",
			"/images/hoteis/family-dog/img-5.jpg",
			"/images/hoteis/family-dog/img-6.jpeg",
			"/images/hoteis/family-dog/img-7.jpg",
		],
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
	},
	// Hotels from Arquipélagos:
	{
		uuid: "1a2b3c4d-0015-0015-0015-000000000015",
		name: "Dogtel",
		region: ["ea3f9a57-2c8b-40d8-8f51-7f9f8d8a27cb"],
		address: "Rua do Lazareto 227, São Gonçalo",
		location: "São Gonçalo",
		lat: 32.649031,
		lng: -16.880921,
		rating: 4,
		contact: "927206258",
		email: "geral@dogtel.pt",
		website: "https://www.dogtel.pt/",
		facebook: "https://www.facebook.com/Dogtel/?locale=pt_PT",
		instagram: "https://www.instagram.com/dogtel_school/",
		petabookPartner: true,
		shortDescription:
			"Dogtel oferece alojamento, treinos, creche e spa para cães e gatos em um espaço de 3000m².",
		longDescription:
			"Localizado na Ilha da Madeira, o Dogtel oferece uma gama completa de serviços para cães e gatos, incluindo alojamento, treinos, creche, spa e consultório veterinário. Conta também com um centro de reabilitação para condições como artrite.",
		services: "Hotel canino",
		prices: 0,
		reservationEmail: "Ricardojesus@dogtel.pt",
		responsableName: "",
		conditions: "",
		workingHours: "",
		images: [
			"/images/hoteis/dogtel/img-1.png",
			"/images/hoteis/dogtel/img-2.png",
			"/images/hoteis/dogtel/img-3.png",
			"/images/hoteis/dogtel/img-4.png",
			"/images/hoteis/dogtel/img-5.png",
			"/images/hoteis/dogtel/img-6.png",
		],
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
	},
	{
		uuid: "1a2b3c4d-0016-0016-0016-000000000016",
		name: "Clínica Veterinária São Miguel",
		region: ["ea3f9a57-2c8b-40d8-8f51-7f9f8d8a27cb"],
		address: "Rua das Mercês 29, Atalhada Lagoa",
		location: "Madeira",
		lat: 37.748071,
		lng: -25.592772,
		rating: 4,
		contact: "968066368",
		email: "geral@cvsm.pt",
		website: "https://www.cvsm.pt/#hotel",
		facebook: "https://www.facebook.com/ClinicaVeterinariaSaoMiguel/",
		instagram: null,
		petabookPartner: false,
		shortDescription:
			"Clínica Veterinária São Miguel dispõe de canis para cães e gatis para gatos, funcionando o ano todo.",
		longDescription:
			"Com 25 canis exteriores, 4 interiores para cães e 21 gatis para gatos, a Clínica Veterinária São Miguel oferece serviços personalizados de alimentação e cuidados, funcionando 365 dias por ano com horários flexíveis.",
		services: "Hotel canino",
		prices: 0,
		reservationEmail: null,
		responsableName: null,
		conditions: "",
		workingHours: "",
		images: [],
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
	},
	// Hotels from Algarve:
	{
		uuid: "1a2b3c4d-0017-0017-0017-000000000017",
		name: "Hotel do Cão Algarve",
		region: ["ae4d2c60-5f3f-4b2d-8e2d-7c2b8b6a9e42"],
		address: "Vale da Rainha, Estrada de Monchique, Portimão",
		location: "Portimão",
		lat: 37.219836,
		lng: -8.544594,
		rating: 4,
		contact: "963876246",
		email: "info@hoteldocao.pt",
		website: "https://www.hoteldocao.pt/",
		facebook: "https://www.facebook.com/hoteldocaoalgarve",
		instagram: "https://www.instagram.com/hoteldocao/",
		petabookPartner: false,
		shortDescription:
			"Hotel do Cão Algarve oferece alojamentos de luxo, praia para cães e SPA, com vigilância veterinária e transporte.",
		longDescription:
			"O Hotel do Cão Algarve proporciona uma experiência única para cães e gatos, com áreas verdes, alojamentos de luxo, praia exclusiva para cães, vigilância veterinária e um SPA que trata de banhos, escovagens e cortes de unhas, além de oferecer serviço de transporte.",
		services: "Hotel canino",
		prices: 0,
		reservationEmail: null,
		responsableName: null,
		conditions: "",
		workingHours: "",
		images: [
			"/images/hoteis/curti-dog/img-1.jpeg",
			"/images/hoteis/curti-dog/img-2.jpeg",
			"/images/hoteis/curti-dog/img-3.jpeg",
			"/images/hoteis/curti-dog/img-4.jpeg",
			"/images/hoteis/curti-dog/img-5.jpeg",
			"/images/hoteis/curti-dog/img-6.jpeg",
			"/images/hoteis/hotel-101/img-1.jpg",
			"/images/hoteis/hotel-101/img-10.jpeg",
			"/images/hoteis/hotel-101/img-11.jpeg",
			"/images/hoteis/hotel-101/img-12.jpeg",
			"/images/hoteis/hotel-101/img-13.jpeg",
			"/images/hoteis/hotel-101/img-14.jpeg",
			"/images/hoteis/hotel-101/img-15.jpeg",
			"/images/hoteis/hotel-101/img-16.jpeg",
			"/images/hoteis/hotel-101/img-17.jpeg",
			"/images/hoteis/hotel-101/img-18.jpeg",
			"/images/hoteis/hotel-101/img-19.jpeg",
			"/images/hoteis/hotel-101/img-2.jpg",
			"/images/hoteis/hotel-101/img-20.jpeg",
			"/images/hoteis/hotel-101/img-21.jpeg",
			"/images/hoteis/hotel-101/img-22.jpeg",
			"/images/hoteis/hotel-101/img-3.jpg",
			"/images/hoteis/hotel-101/img-4.jpg",
			"/images/hoteis/hotel-101/img-5.jpg",
			"/images/hoteis/hotel-101/img-6.jpg",
			"/images/hoteis/hotel-101/img-7.jpg",
			"/images/hoteis/hotel-101/img-8.jpg",
			"/images/hoteis/hotel-101/img-9.jpg",
			"/images/hoteis/just4buddies/img-1.jpg",
			"/images/hoteis/just4buddies/img-2.jpg",
			"/images/hoteis/just4buddies/img-3.jpg",
			"/images/hoteis/just4buddies/img-4.jpg",
			"/images/hoteis/just4buddies/img-5.jpg",
			"/images/hoteis/monte-da-benviuda/img-1.jpg",
			"/images/hoteis/monte-da-benviuda/img-10.jpg",
			"/images/hoteis/monte-da-benviuda/img-11.jpg",
			"/images/hoteis/monte-da-benviuda/img-12.jpg",
			"/images/hoteis/monte-da-benviuda/img-13.jpg",
			"/images/hoteis/monte-da-benviuda/img-2.jpg",
			"/images/hoteis/monte-da-benviuda/img-3.jpg",
			"/images/hoteis/monte-da-benviuda/img-4.jpg",
			"/images/hoteis/monte-da-benviuda/img-5.jpg",
			"/images/hoteis/monte-da-benviuda/img-6.jpg",
			"/images/hoteis/monte-da-benviuda/img-7.jpg",
			"/images/hoteis/monte-da-benviuda/img-8.jpg",
			"/images/hoteis/monte-da-benviuda/img-9.jpg",
			"/images/hoteis/petsInn/img-1.jpeg",
			"/images/hoteis/petsInn/img-10.jpeg",
			"/images/hoteis/petsInn/img-2.jpeg",
			"/images/hoteis/petsInn/img-3.jpeg",
			"/images/hoteis/petsInn/img-4.jpeg",
			"/images/hoteis/petsInn/img-5.jpeg",
			"/images/hoteis/petsInn/img-6.jpeg",
			"/images/hoteis/petsInn/img-7.jpeg",
			"/images/hoteis/petsInn/img-8.jpeg",
			"/images/hoteis/petsInn/img-9.jpeg",
			"/images/hoteis/quinta-da-patada/img-1.jpeg",
			"/images/hoteis/quinta-da-patada/img-2.jpeg",
			"/images/hoteis/quinta-da-patada/img-3.jpeg",
			"/images/hoteis/quinta-da-patada/img-4.jpeg",
			"/images/hoteis/quinta-da-patada/img-5.jpeg",
			"/images/hoteis/quinta-da-patada/img-6.jpeg",
		],
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
	},
	{
		uuid: "1a2b3c4d-0018-0018-0018-000000000018",
		name: "Pets Inn",
		region: ["ae4d2c60-5f3f-4b2d-8e2d-7c2b8b6a9e42"],
		address: "Lugar da Renda, Loulé",
		location: "Loulé",
		lat: 37.146968,
		lng: -8.051465,
		rating: 4.7,
		contact: "915435823",
		email: "contacto@petsinn.pt",
		website: "https://petsinn.pt/",
		facebook: "https://www.facebook.com/petsinnalgarve/",
		instagram: "https://www.instagram.com/petsinn_algarve/",
		petabookPartner: true,
		shortDescription:
			"Pets Inn oferece um ambiente seguro e tranquilo para cães, gatos e outros animais com alojamento e creche canina.",
		longDescription:
			"Localizado no campo em Loulé, Pets Inn oferece um ambiente personalizado para cães, gatos e outras espécies. Além de alojamento temporário, disponibiliza day care com atenção individualizada, acomodando diversos animais em um espaço que proporciona conforto e segurança.",
		services: "Hotel canino",
		prices: 20,
		reservationEmail: "geral@petsinn.pt",
		responsableName: "",
		conditions: "",
		workingHours: "",
		images: [
			"/images/hoteis/pets-inn/img-1.jpg",
			"/images/hoteis/pets-inn/img-10.jpg",
			"/images/hoteis/pets-inn/img-11.jpg",
			"/images/hoteis/pets-inn/img-12.jpg",
			"/images/hoteis/pets-inn/img-13.jpg",
			"/images/hoteis/pets-inn/img-14.jpg",
			"/images/hoteis/pets-inn/img-15.jpg",
			"/images/hoteis/pets-inn/img-16.jpg",
			"/images/hoteis/pets-inn/img-17.jpg",
		],
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
	},
	{
		uuid: "1a2b3c4d-0019-0019-0019-000000000019",
		name: "Dog Spa",
		region: ["ae4d2c60-5f3f-4b2d-8e2d-7c2b8b6a9e42"],
		address: "Monte Escrivão, Sítio da Igreja, Olhão",
		location: "Olhão",
		lat: 37.057183,
		lng: -7.866063,
		rating: 4.7,
		contact: "964639587",
		email: "info@dogspa.com.pt",
		website: "https://www.dogspa.pt/",
		facebook: "https://www.facebook.com/DogSpaQuintaLobos/",
		instagram: "https://www.instagram.com/dogspa_algarve/",
		petabookPartner: false,
		shortDescription:
			"Dog Spa oferece hotel, creche, tosquia, treinos e transporte para cães e gatos, com acompanhamento veterinário.",
		longDescription:
			"A Dog Spa em Olhão conta com instalações projetadas para o conforto e diversão dos animais, com boxes espaçosas e uma área verde vedada para brincadeiras. Uma equipa de profissionais garante a saúde e o bem-estar dos hóspedes, acompanhando-os individualmente.",
		services: "Hotel canino",
		prices: 0,
		reservationEmail: null,
		responsableName: "n.a.",
		conditions: "",
		workingHours: "",
		images: [
			"/images/hoteis/dog-spa/img-1.jpg",
			"/images/hoteis/dog-spa/img-2.jpg",
			"/images/hoteis/dog-spa/img-3.jpg",
			"/images/hoteis/dog-spa/img-4.jpg",
			"/images/hoteis/dog-spa/img-5.jpg",
			"/images/hoteis/dog-spa/img-6.jpg",
			"/images/hoteis/dog-spa/img-7.jpg",
			"/images/hoteis/dog-spa/img-8.jpg",
			"/images/hoteis/dog-spa/img-9.jpg",
		],
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
	},
	{
		uuid: "1a2b3c4d-0020-0020-0020-000000000020",
		name: "Centro Canino do Algarve",
		region: ["ae4d2c60-5f3f-4b2d-8e2d-7c2b8b6a9e42"],
		address: "Estrada municipal nr526 -962 A, Albufeira",
		location: "Albufeira",
		lat: 37.085988,
		lng: -8.287184,
		rating: 4.7,
		contact: "933925808",
		email: "centrocaninoalgarve@gmail.com",
		website: null,
		facebook: "https://www.facebook.com/CCAlgarve/?locale=pt_BR",
		instagram: null,
		petabookPartner: false,
		shortDescription:
			"Centro Canino do Algarve oferece alojamento, passeios, treino e tosquias num ambiente rural com instalações modernas.",
		longDescription:
			"Localizado em Albufeira, o Centro Canino do Algarve oferece serviços para cães, como alojamento, alimentação, passeios, brincadeiras, treino, banhos e tosquias, em um ambiente rural relaxante, com canis individuais e áreas de lazer.",
		services: "Hotel canino",
		prices: 0,
		reservationEmail: null,
		responsableName: null,
		conditions: "",
		workingHours: "",
		images: [
			"/images/hoteis/centro-canino-do-algarve/img-1.jpg",
			"/images/hoteis/centro-canino-do-algarve/img-2.jpg",
			"/images/hoteis/centro-canino-do-algarve/img-3.jpg",
			"/images/hoteis/centro-canino-do-algarve/img-4.jpg",
			"/images/hoteis/centro-canino-do-algarve/img-5.jpg",
		],
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
	},
	{
		uuid: "1a2b3c4d-0021-0021-0021-000000000021",
		name: "Pet Hotel do Algarve",
		region: ["ae4d2c60-5f3f-4b2d-8e2d-7c2b8b6a9e42"],
		address: "Caixa Postal 245-A, Faro",
		location: "Faro",
		lat: 37.125334,
		lng: -7.976966,
		rating: 4.8,
		contact: "960289169",
		email: "pethoteldoalgarve.lda@gmail.com",
		website: "https://www.pethoteldoalgarve.com/",
		facebook: "https://www.facebook.com/pethoteldoalgarve/?locale=pt_PT",
		instagram: "https://www.instagram.com/pet.hotel.do.algarve/",
		petabookPartner: true,
		shortDescription:
			"Pet Hotel do Algarve oferece suítes privativas isotérmicas, passeios diários e apoio veterinário, com transporte especializado.",
		longDescription:
			"O Merrylegs PET Hotel é um hotel familiar que oferece alojamento de luxo, cuidado diário, treino e serviço de entrega e coleta, proporcionando um ambiente seguro para cães, gatos e pequenos animais.",
		services: "Hotel canino",
		prices: 22,
		reservationEmail: "pethoteldoalgarve.lda@gmail.com",
		responsableName: "",
		conditions: "",
		workingHours: "",
		images: [
			"/images/hoteis/pet-hotel-do-algarve/img-1.jpg",
			"/images/hoteis/pet-hotel-do-algarve/img-10.jpg",
			"/images/hoteis/pet-hotel-do-algarve/img-12.jpg",
			"/images/hoteis/pet-hotel-do-algarve/img-6.jpg",
			"/images/hoteis/pet-hotel-do-algarve/img-8.jpg",
		],
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
	},
	{
		uuid: "1a2b3c4d-0022-0022-0022-000000000022",
		name: "Merrylegs Pet Hotel",
		region: ["ae4d2c60-5f3f-4b2d-8e2d-7c2b8b6a9e42"],
		address: "Sitio Estação Loulé 4 Estrada, Loulé",
		location: "Loulé",
		lat: 37.10439,
		lng: -8.059192,
		rating: 4,
		contact: "927296332",
		email: "merrylegspethotel@gmail.com",
		website: "https://www.merrylegspethotel.com/",
		facebook: "https://www.facebook.com/merrylegspethotel",
		instagram:
			"https://www.instagram.com/explore/locations/1019415244/merrylegs-pet-hotel/",
		petabookPartner: false,
		shortDescription:
			"Merrylegs Pet Hotel oferece alojamento de luxo, treino e transporte para cães, gatos e pequenos animais, com 12 anos de experiência.",
		longDescription:
			"O Merrylegs PET Hotel é um hotel familiar que oferece alojamento de luxo, cuidado diário, treino e serviço de entrega e coleta, proporcionando um ambiente seguro e confortável para cães, gatos e pequenos animais, com ênfase no exercício e cuidados diários.",
		services: "Hotel canino",
		prices: 0,
		reservationEmail: null,
		responsableName: null,
		conditions: "",
		workingHours: "",
		images: [
			"/images/hoteis/merrylegs/img-1.png",
			"/images/hoteis/merrylegs/img-2.png",
			"/images/hoteis/merrylegs/img-3.jpg",
			"/images/hoteis/merrylegs/img-4.jpg",
			"/images/hoteis/merrylegs/img-5.jpg",
			"/images/hoteis/merrylegs/img-6.jpg",
		],
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
	},
	{
		uuid: "1a2b3c4d-0023-0023-0023-000000000023",
		name: "Herdade Bonanza",
		region: ["ae4d2c60-5f3f-4b2d-8e2d-7c2b8b6a9e42"],
		address: "Estrada da Barragem, Sitio da Moira 491, Lagos",
		location: "Lagos",
		lat: 37.159396,
		lng: -8.672303,
		rating: 4.9,
		contact: "967344230",
		email: "info@herdadebonanza.com",
		website: "https://www.herdadebonanza.com/",
		facebook: "https://www.facebook.com/hbonanzadogresort/",
		instagram: "https://www.instagram.com/hbonanzadogresort/",
		petabookPartner: false,
		shortDescription:
			"Herdade Bonanza é um resort canino em Lagos com alojamento, creche, treino e transporte, com suítes isoladas e piscina interior.",
		longDescription:
			"A Herdade Bonanza, situada em Lagos, oferece serviços de alojamento, cuidados de higiene, creche, aulas de treino e transporte para cães, com 43 suítes privadas revestidas para isolamento e acesso a piscina interior e áreas monitoradas.",
		services: "Hotel canino",
		prices: 0,
		reservationEmail: null,
		responsableName: null,
		conditions: "",
		workingHours: "",
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
		images: [
			"/images/hoteis/herdade-bonanza/img-1.jpg",
			"/images/hoteis/herdade-bonanza/img-10.jpg",
			"/images/hoteis/herdade-bonanza/img-13.jpg",
			"/images/hoteis/herdade-bonanza/img-15.jpg",
			"/images/hoteis/herdade-bonanza/img-17.jpg",
			"/images/hoteis/herdade-bonanza/img-19.jpg",
			"/images/hoteis/herdade-bonanza/img-6.jpg",
			"/images/hoteis/herdade-bonanza/img-8.jpg",
		],
	},
	{
		uuid: "1a2b3c4d-0024-0024-0024-000000000024",
		name: "Curti Dog",
		region: ["ba9a11fa-3d9d-4d2b-90f8-6b987d0a2c34"],
		address: "Rua Casal da Curtinha 13 2530, Reguengo Grande",
		location: "Reguengo Grande",
		lat: 39.290556,
		lng: -9.226612,
		rating: 4.9,
		contact: "914819881",
		email: "curti_dog@hotmail.com",
		website: null,
		facebook: "https://www.facebook.com/CurtiDog18/?locale=pt_PT",
		instagram: "https://www.instagram.com/curti_dog/",
		petabookPartner: true,
		shortDescription:
			"A Curti Dog oferece hospedagem, creche e estética para cães e gatos, com serviços de petshop, adestramento e transporte.",
		longDescription:
			"Estabelecida em 2018, a Curti Dog é uma empresa familiar que oferece serviços de hospedagem, creche e estética para cães e gatos, com boxes individuais e serviços de adestramento e transporte para consultas veterinárias.",
		services: "Hotel canino",
		prices: 10,
		reservationEmail: "curti_dog@hotmail.com",
		responsableName: "",
		conditions: "",
		workingHours: "",
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
		images: [
			"/images/hoteis/curti-dog/img-1.jpeg",
			"/images/hoteis/curti-dog/img-2.jpeg",
			"/images/hoteis/curti-dog/img-3.jpeg",
			"/images/hoteis/curti-dog/img-4.jpeg",
			"/images/hoteis/curti-dog/img-5.jpeg",
			"/images/hoteis/curti-dog/img-6.jpeg",
		],
	},
	{
		uuid: "1a2b3c4d-0025-0025-0025-000000000025",
		name: "Hotel e Spa Animal VIP",
		region: ["ba9a11fa-3d9d-4d2b-90f8-6b987d0a2c34"],
		address: "Rua da Escola 16, Travassós de Baixo, Viseu",
		location: "Viseu",
		lat: 40.679537,
		lng: -7.883873,
		rating: 4.5,
		contact: "924442759",
		email: "animalvip@ivcevidensia.pt",
		website: "https://www.animalvip.pt/hotel-spa/",
		facebook: "https://www.facebook.com/centroveterinario.beiraalta",
		instagram: "https://www.instagram.com/Animal_vip/",
		petabookPartner: false,
		shortDescription:
			"O Hotel e SPA Animal VIP oferece suites de luxo para cães e gatos com TV, webcam e videochamadas diárias, além de serviços de piscina, grooming e massagens.",
		longDescription:
			"Localizado em Travassós de Baixo, Viseu, o Hotel e SPA Animal VIP proporciona uma experiência de luxo para cães e gatos com suites equipadas com televisão, ventoinha e webcam, passeios diários em um parque vedado de 4000 m², além de serviços de grooming diário, massagens e outras comodidades, funcionando de segunda a sábado.",
		services: "Hotel canino",
		prices: 0,
		reservationEmail: null,
		responsableName: null,
		conditions: "",
		workingHours: "",
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
		images: [
			"/images/hoteis/hotel-e-spa-animal-vip/img-1.png",
			"/images/hoteis/hotel-e-spa-animal-vip/img-10.jpg",
			"/images/hoteis/hotel-e-spa-animal-vip/img-11.jpg",
			"/images/hoteis/hotel-e-spa-animal-vip/img-12.jpg",
			"/images/hoteis/hotel-e-spa-animal-vip/img-2.jpg",
			"/images/hoteis/hotel-e-spa-animal-vip/img-5.png",
		],
	},
	{
		uuid: "1a2b3c4d-0026-0026-0026-000000000026",
		name: "Trela Amarela",
		region: ["ba9a11fa-3d9d-4d2b-90f8-6b987d0a2c34"],
		address: "Rua da Folha 35, Santarém",
		location: "Santarém",
		lat: 39.25506,
		lng: -8.754333,
		rating: 5,
		contact: "938503142",
		email: null,
		website: "https://trelaamarela.pt/pet-hotel/",
		facebook: "https://www.facebook.com/Trela.Amarela/?locale=pt_PT",
		instagram: "https://www.instagram.com/atrelaamarela/",
		petabookPartner: false,
		shortDescription:
			"O Hotel d’A Trela Amarela oferece alojamento para cães e gatos com amplos espaços vedados, passeios diários e monitorização veterinária.",
		longDescription:
			"Situado numa zona rural a 5 minutos da A1 em Santarém, o Hotel d’A Trela Amarela dispõe de 20 boxes para cães e 10 para gatos, com dois passeios diários em um espaço de 15.000 m². Os check-ins ocorrem das 9h às 11h e os check-outs das 16h às 18h, com filmagens das brincadeiras para os donos.",
		services: "Hotel canino",
		prices: 14,
		reservationEmail: null,
		responsableName: null,
		conditions: "",
		workingHours: "",
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
		images: [
			"/images/hoteis/trela-amarela/img-1.jpg",
			"/images/hoteis/trela-amarela/img-10.jpg",
			"/images/hoteis/trela-amarela/img-11.jpg",
			"/images/hoteis/trela-amarela/img-12.jpg",
			"/images/hoteis/trela-amarela/img-13.jpg",
			"/images/hoteis/trela-amarela/img-14.jpg",
			"/images/hoteis/trela-amarela/img-15.jpg",
		],
	},
	// Hotels from Alentejo:
	{
		uuid: "1a2b3c4d-0027-0027-0027-000000000027",
		name: "Monte da Benviuda",
		region: ["d1a5a76f-7a8f-4b92-9a3f-abc1d1e2f345"],
		address: "Monte da Benviuda, Alcaria Ruiva, Mértola",
		location: "Mértola",
		lat: 37.711814,
		lng: -7.8394,
		rating: 4.7,
		contact: "963187118",
		email: "canilmontedabenviuda.blogspot.pt",
		website: null,
		facebook:
			"https://www.facebook.com/p/Canil-Monte-da-Benviuda-100063803253210/",
		instagram: "https://www.instagram.com/canil.monte.da.benviuda/",
		petabookPartner: true,
		shortDescription:
			"Monte da Benviuda oferece alojamento tranquilo para cães com boxes individuais, parque de passeios e centro de estética canina.",
		longDescription:
			"Localizado em Mértola, o Hotel Canino 'Monte da Benviúda' oferece tratamento personalizado e um ambiente acolhedor, com boxes individuais, um parque para passeios e um centro de estética canina, proporcionando um espaço seguro para os animais.",
		services: "Hotel canino",
		prices: 12,
		reservationEmail: "Monte.da.benviuda@sapo.pt",
		responsableName: "",
		conditions: "",
		workingHours: "",
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
		images: [
			"/images/hoteis/monte-da-benviuda/img-1.jpg",
			"/images/hoteis/monte-da-benviuda/img-10.jpg",
			"/images/hoteis/monte-da-benviuda/img-11.jpg",
			"/images/hoteis/monte-da-benviuda/img-12.jpg",
			"/images/hoteis/monte-da-benviuda/img-13.jpg",
			"/images/hoteis/monte-da-benviuda/img-2.jpg",
			"/images/hoteis/monte-da-benviuda/img-3.jpg",
			"/images/hoteis/monte-da-benviuda/img-4.jpg",
			"/images/hoteis/monte-da-benviuda/img-5.jpg",
			"/images/hoteis/monte-da-benviuda/img-6.jpg",
			"/images/hoteis/monte-da-benviuda/img-7.jpg",
			"/images/hoteis/monte-da-benviuda/img-8.jpg",
			"/images/hoteis/monte-da-benviuda/img-9.jpg",
		],
	},
	{
		uuid: "1a2b3c4d-0028-0028-0028-000000000028",
		name: "Residência Canina e Felina",
		region: ["d1a5a76f-7a8f-4b92-9a3f-abc1d1e2f345"],
		address: "Fonte Santa Estrada da Calçadinha, CP 219, Elvas",
		location: "Elvas",
		lat: 38.88296,
		lng: -7.19067,
		rating: 4.7,
		contact: "268622607",
		email: "geral.pethotel@fortedelvas.pt",
		website: "https://www.residenciacanina.pt/pt/canina.php",
		facebook:
			"https://www.facebook.com/residenciacaninafortedelvas/?locale=pt_PT",
		instagram: "https://www.instagram.com/residenciacaninafelina/",
		petabookPartner: false,
		shortDescription:
			"Residência Canina e Felina Forte de Elvas oferece alojamento seguro para cães e gatos, com treinos e cuidados veterinários.",
		longDescription:
			"Localizada em Elvas, a Residência Canina e Felina Forte de Elvas é dedicada ao cuidado dos animais, oferecendo serviços de hospedagem, cuidados diários, treinos e serviços veterinários em um ambiente seguro e confortável.",
		services: "Hotel canino",
		prices: 12,
		reservationEmail: null,
		responsableName: null,
		conditions: "",
		workingHours: "",
		checkInHours: "",
		checkOutHours: "",
		checkInDays: "",
		checkOutDays: "",
		restrictions: "",
		images: [
			"/images/hoteis/residencia-canina-e-felina/img-1.jpg",
			"/images/hoteis/residencia-canina-e-felina/img-10.jpg",
			"/images/hoteis/residencia-canina-e-felina/img-11.jpg",
			"/images/hoteis/residencia-canina-e-felina/img-12.jpg",
		],
	},
];

// Build an object keyed by the hotel uuid for easy lookup.
export const hotelObj: HotelData = hotelList.reduce((acc, hotel) => {
	acc[hotel.uuid] = hotel;
	return acc;
}, {} as HotelData);
